// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// ExportBookingForEditOKCode is the HTTP code returned for type ExportBookingForEditOK
const ExportBookingForEditOKCode int = 200

/*
ExportBookingForEditOK OK

swagger:response exportBookingForEditOK
*/
type ExportBookingForEditOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookingEdit `json:"body,omitempty"`
}

// NewExportBookingForEditOK creates ExportBookingForEditOK with default headers values
func NewExportBookingForEditOK() *ExportBookingForEditOK {

	return &ExportBookingForEditOK{}
}

// WithPayload adds the payload to the export booking for edit o k response
func (o *ExportBookingForEditOK) WithPayload(payload *models.BookingEdit) *ExportBookingForEditOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export booking for edit o k response
func (o *ExportBookingForEditOK) SetPayload(payload *models.BookingEdit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportBookingForEditOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportBookingForEditUnauthorizedCode is the HTTP code returned for type ExportBookingForEditUnauthorized
const ExportBookingForEditUnauthorizedCode int = 401

/*
ExportBookingForEditUnauthorized Unauthorized

swagger:response exportBookingForEditUnauthorized
*/
type ExportBookingForEditUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewExportBookingForEditUnauthorized creates ExportBookingForEditUnauthorized with default headers values
func NewExportBookingForEditUnauthorized() *ExportBookingForEditUnauthorized {

	return &ExportBookingForEditUnauthorized{}
}

// WithPayload adds the payload to the export booking for edit unauthorized response
func (o *ExportBookingForEditUnauthorized) WithPayload(payload *models.Error) *ExportBookingForEditUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export booking for edit unauthorized response
func (o *ExportBookingForEditUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportBookingForEditUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportBookingForEditNotFoundCode is the HTTP code returned for type ExportBookingForEditNotFound
const ExportBookingForEditNotFoundCode int = 404

/*
ExportBookingForEditNotFound The specified resource was not found

swagger:response exportBookingForEditNotFound
*/
type ExportBookingForEditNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewExportBookingForEditNotFound creates ExportBookingForEditNotFound with default headers values
func NewExportBookingForEditNotFound() *ExportBookingForEditNotFound {

	return &ExportBookingForEditNotFound{}
}

// WithPayload adds the payload to the export booking for edit not found response
func (o *ExportBookingForEditNotFound) WithPayload(payload *models.Error) *ExportBookingForEditNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export booking for edit not found response
func (o *ExportBookingForEditNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportBookingForEditNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ExportBookingForEditInternalServerErrorCode is the HTTP code returned for type ExportBookingForEditInternalServerError
const ExportBookingForEditInternalServerErrorCode int = 500

/*
ExportBookingForEditInternalServerError Internal Error

swagger:response exportBookingForEditInternalServerError
*/
type ExportBookingForEditInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewExportBookingForEditInternalServerError creates ExportBookingForEditInternalServerError with default headers values
func NewExportBookingForEditInternalServerError() *ExportBookingForEditInternalServerError {

	return &ExportBookingForEditInternalServerError{}
}

// WithPayload adds the payload to the export booking for edit internal server error response
func (o *ExportBookingForEditInternalServerError) WithPayload(payload *models.Error) *ExportBookingForEditInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the export booking for edit internal server error response
func (o *ExportBookingForEditInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ExportBookingForEditInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
