// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ExportBookingForEditHandlerFunc turns a function with the right signature into a export booking for edit handler
type ExportBookingForEditHandlerFunc func(ExportBookingForEditParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ExportBookingForEditHandlerFunc) Handle(params ExportBookingForEditParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ExportBookingForEditHandler interface for that can handle valid export booking for edit params
type ExportBookingForEditHandler interface {
	Handle(ExportBookingForEditParams, interface{}) middleware.Responder
}

// NewExportBookingForEdit creates a new http.Handler for the export booking for edit operation
func NewExportBookingForEdit(ctx *middleware.Context, handler ExportBookingForEditHandler) *ExportBookingForEdit {
	return &ExportBookingForEdit{Context: ctx, Handler: handler}
}

/*
	ExportBookingForEdit swagger:route GET /admin/bookings/{booking_name} admin exportBookingForEdit

# Export one current booking for editing

Returns the booking together with the opaque revision required to replace it. Preserve the envelope when editing and upload it with PUT.
*/
type ExportBookingForEdit struct {
	Context *middleware.Context
	Handler ExportBookingForEditHandler
}

func (o *ExportBookingForEdit) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewExportBookingForEditParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
