// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetResourceIsAvailableHandlerFunc turns a function with the right signature into a get resource is available handler
type GetResourceIsAvailableHandlerFunc func(GetResourceIsAvailableParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetResourceIsAvailableHandlerFunc) Handle(params GetResourceIsAvailableParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetResourceIsAvailableHandler interface for that can handle valid get resource is available params
type GetResourceIsAvailableHandler interface {
	Handle(GetResourceIsAvailableParams, interface{}) middleware.Responder
}

// NewGetResourceIsAvailable creates a new http.Handler for the get resource is available operation
func NewGetResourceIsAvailable(ctx *middleware.Context, handler GetResourceIsAvailableHandler) *GetResourceIsAvailable {
	return &GetResourceIsAvailable{Context: ctx, Handler: handler}
}

/* GetResourceIsAvailable swagger:route GET /admin/resources/{resource_name} admin getResourceIsAvailable

Get the availability of the resource

Gets the availability of the underlying resource for the slot, including a status message. Indicates when equipment is offline temprorarily, e.g. due to failing an automated test.

*/
type GetResourceIsAvailable struct {
	Context *middleware.Context
	Handler GetResourceIsAvailableHandler
}

func (o *GetResourceIsAvailable) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetResourceIsAvailableParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
