// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// GetBookingEventsOKCode is the HTTP code returned for type GetBookingEventsOK
const GetBookingEventsOKCode int = 200

/*
GetBookingEventsOK OK

swagger:response getBookingEventsOK
*/
type GetBookingEventsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.BookingEvent `json:"body,omitempty"`
}

// NewGetBookingEventsOK creates GetBookingEventsOK with default headers values
func NewGetBookingEventsOK() *GetBookingEventsOK {

	return &GetBookingEventsOK{}
}

// WithPayload adds the payload to the get booking events o k response
func (o *GetBookingEventsOK) WithPayload(payload []*models.BookingEvent) *GetBookingEventsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking events o k response
func (o *GetBookingEventsOK) SetPayload(payload []*models.BookingEvent) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingEventsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.BookingEvent, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetBookingEventsUnauthorizedCode is the HTTP code returned for type GetBookingEventsUnauthorized
const GetBookingEventsUnauthorizedCode int = 401

/*
GetBookingEventsUnauthorized Unauthorized

swagger:response getBookingEventsUnauthorized
*/
type GetBookingEventsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBookingEventsUnauthorized creates GetBookingEventsUnauthorized with default headers values
func NewGetBookingEventsUnauthorized() *GetBookingEventsUnauthorized {

	return &GetBookingEventsUnauthorized{}
}

// WithPayload adds the payload to the get booking events unauthorized response
func (o *GetBookingEventsUnauthorized) WithPayload(payload *models.Error) *GetBookingEventsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking events unauthorized response
func (o *GetBookingEventsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingEventsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBookingEventsNotFoundCode is the HTTP code returned for type GetBookingEventsNotFound
const GetBookingEventsNotFoundCode int = 404

/*
GetBookingEventsNotFound The specified resource was not found

swagger:response getBookingEventsNotFound
*/
type GetBookingEventsNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBookingEventsNotFound creates GetBookingEventsNotFound with default headers values
func NewGetBookingEventsNotFound() *GetBookingEventsNotFound {

	return &GetBookingEventsNotFound{}
}

// WithPayload adds the payload to the get booking events not found response
func (o *GetBookingEventsNotFound) WithPayload(payload *models.Error) *GetBookingEventsNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking events not found response
func (o *GetBookingEventsNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingEventsNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBookingEventsInternalServerErrorCode is the HTTP code returned for type GetBookingEventsInternalServerError
const GetBookingEventsInternalServerErrorCode int = 500

/*
GetBookingEventsInternalServerError Internal Error

swagger:response getBookingEventsInternalServerError
*/
type GetBookingEventsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBookingEventsInternalServerError creates GetBookingEventsInternalServerError with default headers values
func NewGetBookingEventsInternalServerError() *GetBookingEventsInternalServerError {

	return &GetBookingEventsInternalServerError{}
}

// WithPayload adds the payload to the get booking events internal server error response
func (o *GetBookingEventsInternalServerError) WithPayload(payload *models.Error) *GetBookingEventsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get booking events internal server error response
func (o *GetBookingEventsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBookingEventsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
