// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// ListResourceHoldsOKCode is the HTTP code returned for type ListResourceHoldsOK
const ListResourceHoldsOKCode int = 200

/*
ListResourceHoldsOK OK

swagger:response listResourceHoldsOK
*/
type ListResourceHoldsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ResourceHold `json:"body,omitempty"`
}

// NewListResourceHoldsOK creates ListResourceHoldsOK with default headers values
func NewListResourceHoldsOK() *ListResourceHoldsOK {

	return &ListResourceHoldsOK{}
}

// WithPayload adds the payload to the list resource holds o k response
func (o *ListResourceHoldsOK) WithPayload(payload []*models.ResourceHold) *ListResourceHoldsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource holds o k response
func (o *ListResourceHoldsOK) SetPayload(payload []*models.ResourceHold) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceHoldsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ResourceHold, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListResourceHoldsUnauthorizedCode is the HTTP code returned for type ListResourceHoldsUnauthorized
const ListResourceHoldsUnauthorizedCode int = 401

/*
ListResourceHoldsUnauthorized Unauthorized

swagger:response listResourceHoldsUnauthorized
*/
type ListResourceHoldsUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListResourceHoldsUnauthorized creates ListResourceHoldsUnauthorized with default headers values
func NewListResourceHoldsUnauthorized() *ListResourceHoldsUnauthorized {

	return &ListResourceHoldsUnauthorized{}
}

// WithPayload adds the payload to the list resource holds unauthorized response
func (o *ListResourceHoldsUnauthorized) WithPayload(payload *models.Error) *ListResourceHoldsUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource holds unauthorized response
func (o *ListResourceHoldsUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceHoldsUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListResourceHoldsInternalServerErrorCode is the HTTP code returned for type ListResourceHoldsInternalServerError
const ListResourceHoldsInternalServerErrorCode int = 500

/*
ListResourceHoldsInternalServerError Internal Error

swagger:response listResourceHoldsInternalServerError
*/
type ListResourceHoldsInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListResourceHoldsInternalServerError creates ListResourceHoldsInternalServerError with default headers values
func NewListResourceHoldsInternalServerError() *ListResourceHoldsInternalServerError {

	return &ListResourceHoldsInternalServerError{}
}

// WithPayload adds the payload to the list resource holds internal server error response
func (o *ListResourceHoldsInternalServerError) WithPayload(payload *models.Error) *ListResourceHoldsInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource holds internal server error response
func (o *ListResourceHoldsInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceHoldsInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
