// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// ListResourceReleasesOKCode is the HTTP code returned for type ListResourceReleasesOK
const ListResourceReleasesOKCode int = 200

/*
ListResourceReleasesOK OK

swagger:response listResourceReleasesOK
*/
type ListResourceReleasesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.ResourceReleaseState `json:"body,omitempty"`
}

// NewListResourceReleasesOK creates ListResourceReleasesOK with default headers values
func NewListResourceReleasesOK() *ListResourceReleasesOK {

	return &ListResourceReleasesOK{}
}

// WithPayload adds the payload to the list resource releases o k response
func (o *ListResourceReleasesOK) WithPayload(payload []*models.ResourceReleaseState) *ListResourceReleasesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource releases o k response
func (o *ListResourceReleasesOK) SetPayload(payload []*models.ResourceReleaseState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceReleasesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.ResourceReleaseState, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// ListResourceReleasesUnauthorizedCode is the HTTP code returned for type ListResourceReleasesUnauthorized
const ListResourceReleasesUnauthorizedCode int = 401

/*
ListResourceReleasesUnauthorized Unauthorized

swagger:response listResourceReleasesUnauthorized
*/
type ListResourceReleasesUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListResourceReleasesUnauthorized creates ListResourceReleasesUnauthorized with default headers values
func NewListResourceReleasesUnauthorized() *ListResourceReleasesUnauthorized {

	return &ListResourceReleasesUnauthorized{}
}

// WithPayload adds the payload to the list resource releases unauthorized response
func (o *ListResourceReleasesUnauthorized) WithPayload(payload *models.Error) *ListResourceReleasesUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource releases unauthorized response
func (o *ListResourceReleasesUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceReleasesUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ListResourceReleasesInternalServerErrorCode is the HTTP code returned for type ListResourceReleasesInternalServerError
const ListResourceReleasesInternalServerErrorCode int = 500

/*
ListResourceReleasesInternalServerError Internal Error

swagger:response listResourceReleasesInternalServerError
*/
type ListResourceReleasesInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewListResourceReleasesInternalServerError creates ListResourceReleasesInternalServerError with default headers values
func NewListResourceReleasesInternalServerError() *ListResourceReleasesInternalServerError {

	return &ListResourceReleasesInternalServerError{}
}

// WithPayload adds the payload to the list resource releases internal server error response
func (o *ListResourceReleasesInternalServerError) WithPayload(payload *models.Error) *ListResourceReleasesInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list resource releases internal server error response
func (o *ListResourceReleasesInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListResourceReleasesInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
