// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListOperationalHealthHandlerFunc turns a function with the right signature into a list operational health handler
type ListOperationalHealthHandlerFunc func(ListOperationalHealthParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListOperationalHealthHandlerFunc) Handle(params ListOperationalHealthParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListOperationalHealthHandler interface for that can handle valid list operational health params
type ListOperationalHealthHandler interface {
	Handle(ListOperationalHealthParams, interface{}) middleware.Responder
}

// NewListOperationalHealth creates a new http.Handler for the list operational health operation
func NewListOperationalHealth(ctx *middleware.Context, handler ListOperationalHealthHandler) *ListOperationalHealth {
	return &ListOperationalHealth{Context: ctx, Handler: handler}
}

/*
	ListOperationalHealth swagger:route GET /admin/operational-health admin listOperationalHealth

List latest automated stream-health decisions
*/
type ListOperationalHealth struct {
	Context *middleware.Context
	Handler ListOperationalHealthHandler
}

func (o *ListOperationalHealth) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListOperationalHealthParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
