// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListOperationalOccurrencesHandlerFunc turns a function with the right signature into a list operational occurrences handler
type ListOperationalOccurrencesHandlerFunc func(ListOperationalOccurrencesParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn ListOperationalOccurrencesHandlerFunc) Handle(params ListOperationalOccurrencesParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// ListOperationalOccurrencesHandler interface for that can handle valid list operational occurrences params
type ListOperationalOccurrencesHandler interface {
	Handle(ListOperationalOccurrencesParams, interface{}) middleware.Responder
}

// NewListOperationalOccurrences creates a new http.Handler for the list operational occurrences operation
func NewListOperationalOccurrences(ctx *middleware.Context, handler ListOperationalOccurrencesHandler) *ListOperationalOccurrences {
	return &ListOperationalOccurrences{Context: ctx, Handler: handler}
}

/*
	ListOperationalOccurrences swagger:route GET /admin/operational-occurrences admin listOperationalOccurrences

# List scheduled operational occurrences

Returns a bounded authoritative list of planned, skipped, conflicted, or missed schedule occurrences.
*/
type ListOperationalOccurrences struct {
	Context *middleware.Context
	Handler ListOperationalOccurrencesHandler
}

func (o *ListOperationalOccurrences) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListOperationalOccurrencesParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
