// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewListOperationalOccurrencesParams creates a new ListOperationalOccurrencesParams object
// with the default values initialized.
func NewListOperationalOccurrencesParams() ListOperationalOccurrencesParams {

	var (
		// initialize parameters with default values

		limitDefault = int64(200)
	)

	return ListOperationalOccurrencesParams{
		Limit: &limitDefault,
	}
}

// ListOperationalOccurrencesParams contains all the bound params for the list operational occurrences operation
// typically these are obtained from a http.Request
//
// swagger:parameters ListOperationalOccurrences
type ListOperationalOccurrencesParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	From *strfmt.DateTime
	/*
	  Maximum: 500
	  Minimum: 1
	  In: query
	  Default: 200
	*/
	Limit *int64
	/*
	  In: query
	*/
	State *string
	/*
	  In: query
	*/
	Until *strfmt.DateTime
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListOperationalOccurrencesParams() beforehand.
func (o *ListOperationalOccurrencesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qFrom, qhkFrom, _ := qs.GetOK("from")
	if err := o.bindFrom(qFrom, qhkFrom, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qState, qhkState, _ := qs.GetOK("state")
	if err := o.bindState(qState, qhkState, route.Formats); err != nil {
		res = append(res, err)
	}

	qUntil, qhkUntil, _ := qs.GetOK("until")
	if err := o.bindUntil(qUntil, qhkUntil, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindFrom binds and validates parameter From from query.
func (o *ListOperationalOccurrencesParams) bindFrom(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("from", "query", "strfmt.DateTime", raw)
	}
	o.From = (value.(*strfmt.DateTime))

	if err := o.validateFrom(formats); err != nil {
		return err
	}

	return nil
}

// validateFrom carries on validations for parameter From
func (o *ListOperationalOccurrencesParams) validateFrom(formats strfmt.Registry) error {

	if err := validate.FormatOf("from", "query", "date-time", o.From.String(), formats); err != nil {
		return err
	}
	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *ListOperationalOccurrencesParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewListOperationalOccurrencesParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	if err := o.validateLimit(formats); err != nil {
		return err
	}

	return nil
}

// validateLimit carries on validations for parameter Limit
func (o *ListOperationalOccurrencesParams) validateLimit(formats strfmt.Registry) error {

	if err := validate.MinimumInt("limit", "query", *o.Limit, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("limit", "query", *o.Limit, 500, false); err != nil {
		return err
	}

	return nil
}

// bindState binds and validates parameter State from query.
func (o *ListOperationalOccurrencesParams) bindState(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.State = &raw

	if err := o.validateState(formats); err != nil {
		return err
	}

	return nil
}

// validateState carries on validations for parameter State
func (o *ListOperationalOccurrencesParams) validateState(formats strfmt.Registry) error {

	if err := validate.EnumCase("state", "query", *o.State, []interface{}{"planned", "skipped", "conflict", "missed"}, true); err != nil {
		return err
	}

	return nil
}

// bindUntil binds and validates parameter Until from query.
func (o *ListOperationalOccurrencesParams) bindUntil(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}

	// Format: date-time
	value, err := formats.Parse("date-time", raw)
	if err != nil {
		return errors.InvalidType("until", "query", "strfmt.DateTime", raw)
	}
	o.Until = (value.(*strfmt.DateTime))

	if err := o.validateUntil(formats); err != nil {
		return err
	}

	return nil
}

// validateUntil carries on validations for parameter Until
func (o *ListOperationalOccurrencesParams) validateUntil(formats strfmt.Registry) error {

	if err := validate.FormatOf("until", "query", "date-time", o.Until.String(), formats); err != nil {
		return err
	}
	return nil
}
