// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
)

// MakeMaintenanceBookingURL generates an URL for the make maintenance booking operation
type MakeMaintenanceBookingURL struct {
	From     strfmt.DateTime
	SlotName string
	To       strfmt.DateTime

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *MakeMaintenanceBookingURL) WithBasePath(bp string) *MakeMaintenanceBookingURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *MakeMaintenanceBookingURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *MakeMaintenanceBookingURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/admin/maintenance/bookings"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	fromQ := o.From.String()
	if fromQ != "" {
		qs.Set("from", fromQ)
	}

	slotNameQ := o.SlotName
	if slotNameQ != "" {
		qs.Set("slot_name", slotNameQ)
	}

	toQ := o.To.String()
	if toQ != "" {
		qs.Set("to", toQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *MakeMaintenanceBookingURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *MakeMaintenanceBookingURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *MakeMaintenanceBookingURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on MakeMaintenanceBookingURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on MakeMaintenanceBookingURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *MakeMaintenanceBookingURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
