// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// MakeMaintenanceBookingOKCode is the HTTP code returned for type MakeMaintenanceBookingOK
const MakeMaintenanceBookingOKCode int = 200

/*
MakeMaintenanceBookingOK OK

swagger:response makeMaintenanceBookingOK
*/
type MakeMaintenanceBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Booking `json:"body,omitempty"`
}

// NewMakeMaintenanceBookingOK creates MakeMaintenanceBookingOK with default headers values
func NewMakeMaintenanceBookingOK() *MakeMaintenanceBookingOK {

	return &MakeMaintenanceBookingOK{}
}

// WithPayload adds the payload to the make maintenance booking o k response
func (o *MakeMaintenanceBookingOK) WithPayload(payload *models.Booking) *MakeMaintenanceBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make maintenance booking o k response
func (o *MakeMaintenanceBookingOK) SetPayload(payload *models.Booking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeMaintenanceBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeMaintenanceBookingUnauthorizedCode is the HTTP code returned for type MakeMaintenanceBookingUnauthorized
const MakeMaintenanceBookingUnauthorizedCode int = 401

/*
MakeMaintenanceBookingUnauthorized Unauthorized

swagger:response makeMaintenanceBookingUnauthorized
*/
type MakeMaintenanceBookingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeMaintenanceBookingUnauthorized creates MakeMaintenanceBookingUnauthorized with default headers values
func NewMakeMaintenanceBookingUnauthorized() *MakeMaintenanceBookingUnauthorized {

	return &MakeMaintenanceBookingUnauthorized{}
}

// WithPayload adds the payload to the make maintenance booking unauthorized response
func (o *MakeMaintenanceBookingUnauthorized) WithPayload(payload *models.Error) *MakeMaintenanceBookingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make maintenance booking unauthorized response
func (o *MakeMaintenanceBookingUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeMaintenanceBookingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeMaintenanceBookingNotFoundCode is the HTTP code returned for type MakeMaintenanceBookingNotFound
const MakeMaintenanceBookingNotFoundCode int = 404

/*
MakeMaintenanceBookingNotFound The specified resource was not found

swagger:response makeMaintenanceBookingNotFound
*/
type MakeMaintenanceBookingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeMaintenanceBookingNotFound creates MakeMaintenanceBookingNotFound with default headers values
func NewMakeMaintenanceBookingNotFound() *MakeMaintenanceBookingNotFound {

	return &MakeMaintenanceBookingNotFound{}
}

// WithPayload adds the payload to the make maintenance booking not found response
func (o *MakeMaintenanceBookingNotFound) WithPayload(payload *models.Error) *MakeMaintenanceBookingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make maintenance booking not found response
func (o *MakeMaintenanceBookingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeMaintenanceBookingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeMaintenanceBookingConflictCode is the HTTP code returned for type MakeMaintenanceBookingConflict
const MakeMaintenanceBookingConflictCode int = 409

/*
MakeMaintenanceBookingConflict The booking was changed, started, or conflicts with the proposed replacement

swagger:response makeMaintenanceBookingConflict
*/
type MakeMaintenanceBookingConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeMaintenanceBookingConflict creates MakeMaintenanceBookingConflict with default headers values
func NewMakeMaintenanceBookingConflict() *MakeMaintenanceBookingConflict {

	return &MakeMaintenanceBookingConflict{}
}

// WithPayload adds the payload to the make maintenance booking conflict response
func (o *MakeMaintenanceBookingConflict) WithPayload(payload *models.Error) *MakeMaintenanceBookingConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make maintenance booking conflict response
func (o *MakeMaintenanceBookingConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeMaintenanceBookingConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeMaintenanceBookingInternalServerErrorCode is the HTTP code returned for type MakeMaintenanceBookingInternalServerError
const MakeMaintenanceBookingInternalServerErrorCode int = 500

/*
MakeMaintenanceBookingInternalServerError Internal Error

swagger:response makeMaintenanceBookingInternalServerError
*/
type MakeMaintenanceBookingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeMaintenanceBookingInternalServerError creates MakeMaintenanceBookingInternalServerError with default headers values
func NewMakeMaintenanceBookingInternalServerError() *MakeMaintenanceBookingInternalServerError {

	return &MakeMaintenanceBookingInternalServerError{}
}

// WithPayload adds the payload to the make maintenance booking internal server error response
func (o *MakeMaintenanceBookingInternalServerError) WithPayload(payload *models.Error) *MakeMaintenanceBookingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make maintenance booking internal server error response
func (o *MakeMaintenanceBookingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeMaintenanceBookingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
