// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// MakeResourceMaintenanceBookingOKCode is the HTTP code returned for type MakeResourceMaintenanceBookingOK
const MakeResourceMaintenanceBookingOKCode int = 200

/*
MakeResourceMaintenanceBookingOK OK

swagger:response makeResourceMaintenanceBookingOK
*/
type MakeResourceMaintenanceBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Booking `json:"body,omitempty"`
}

// NewMakeResourceMaintenanceBookingOK creates MakeResourceMaintenanceBookingOK with default headers values
func NewMakeResourceMaintenanceBookingOK() *MakeResourceMaintenanceBookingOK {

	return &MakeResourceMaintenanceBookingOK{}
}

// WithPayload adds the payload to the make resource maintenance booking o k response
func (o *MakeResourceMaintenanceBookingOK) WithPayload(payload *models.Booking) *MakeResourceMaintenanceBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make resource maintenance booking o k response
func (o *MakeResourceMaintenanceBookingOK) SetPayload(payload *models.Booking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeResourceMaintenanceBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeResourceMaintenanceBookingUnauthorizedCode is the HTTP code returned for type MakeResourceMaintenanceBookingUnauthorized
const MakeResourceMaintenanceBookingUnauthorizedCode int = 401

/*
MakeResourceMaintenanceBookingUnauthorized Unauthorized

swagger:response makeResourceMaintenanceBookingUnauthorized
*/
type MakeResourceMaintenanceBookingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeResourceMaintenanceBookingUnauthorized creates MakeResourceMaintenanceBookingUnauthorized with default headers values
func NewMakeResourceMaintenanceBookingUnauthorized() *MakeResourceMaintenanceBookingUnauthorized {

	return &MakeResourceMaintenanceBookingUnauthorized{}
}

// WithPayload adds the payload to the make resource maintenance booking unauthorized response
func (o *MakeResourceMaintenanceBookingUnauthorized) WithPayload(payload *models.Error) *MakeResourceMaintenanceBookingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make resource maintenance booking unauthorized response
func (o *MakeResourceMaintenanceBookingUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeResourceMaintenanceBookingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeResourceMaintenanceBookingNotFoundCode is the HTTP code returned for type MakeResourceMaintenanceBookingNotFound
const MakeResourceMaintenanceBookingNotFoundCode int = 404

/*
MakeResourceMaintenanceBookingNotFound The specified resource was not found

swagger:response makeResourceMaintenanceBookingNotFound
*/
type MakeResourceMaintenanceBookingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeResourceMaintenanceBookingNotFound creates MakeResourceMaintenanceBookingNotFound with default headers values
func NewMakeResourceMaintenanceBookingNotFound() *MakeResourceMaintenanceBookingNotFound {

	return &MakeResourceMaintenanceBookingNotFound{}
}

// WithPayload adds the payload to the make resource maintenance booking not found response
func (o *MakeResourceMaintenanceBookingNotFound) WithPayload(payload *models.Error) *MakeResourceMaintenanceBookingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make resource maintenance booking not found response
func (o *MakeResourceMaintenanceBookingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeResourceMaintenanceBookingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeResourceMaintenanceBookingConflictCode is the HTTP code returned for type MakeResourceMaintenanceBookingConflict
const MakeResourceMaintenanceBookingConflictCode int = 409

/*
MakeResourceMaintenanceBookingConflict The booking was changed, started, or conflicts with the proposed replacement

swagger:response makeResourceMaintenanceBookingConflict
*/
type MakeResourceMaintenanceBookingConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeResourceMaintenanceBookingConflict creates MakeResourceMaintenanceBookingConflict with default headers values
func NewMakeResourceMaintenanceBookingConflict() *MakeResourceMaintenanceBookingConflict {

	return &MakeResourceMaintenanceBookingConflict{}
}

// WithPayload adds the payload to the make resource maintenance booking conflict response
func (o *MakeResourceMaintenanceBookingConflict) WithPayload(payload *models.Error) *MakeResourceMaintenanceBookingConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make resource maintenance booking conflict response
func (o *MakeResourceMaintenanceBookingConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeResourceMaintenanceBookingConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeResourceMaintenanceBookingInternalServerErrorCode is the HTTP code returned for type MakeResourceMaintenanceBookingInternalServerError
const MakeResourceMaintenanceBookingInternalServerErrorCode int = 500

/*
MakeResourceMaintenanceBookingInternalServerError Internal Error

swagger:response makeResourceMaintenanceBookingInternalServerError
*/
type MakeResourceMaintenanceBookingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeResourceMaintenanceBookingInternalServerError creates MakeResourceMaintenanceBookingInternalServerError with default headers values
func NewMakeResourceMaintenanceBookingInternalServerError() *MakeResourceMaintenanceBookingInternalServerError {

	return &MakeResourceMaintenanceBookingInternalServerError{}
}

// WithPayload adds the payload to the make resource maintenance booking internal server error response
func (o *MakeResourceMaintenanceBookingInternalServerError) WithPayload(payload *models.Error) *MakeResourceMaintenanceBookingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make resource maintenance booking internal server error response
func (o *MakeResourceMaintenanceBookingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeResourceMaintenanceBookingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
