// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// QueryBookingRecordsURL generates an URL for the query booking records operation
type QueryBookingRecordsURL struct {
	From     *strfmt.DateTime
	Limit    *int64
	Policy   *string
	Resource *string
	Slot     *string
	State    *string
	To       *strfmt.DateTime
	User     *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *QueryBookingRecordsURL) WithBasePath(bp string) *QueryBookingRecordsURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *QueryBookingRecordsURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *QueryBookingRecordsURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/admin/booking-records"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var fromQ string
	if o.From != nil {
		fromQ = o.From.String()
	}
	if fromQ != "" {
		qs.Set("from", fromQ)
	}

	var limitQ string
	if o.Limit != nil {
		limitQ = swag.FormatInt64(*o.Limit)
	}
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	var policyQ string
	if o.Policy != nil {
		policyQ = *o.Policy
	}
	if policyQ != "" {
		qs.Set("policy", policyQ)
	}

	var resourceQ string
	if o.Resource != nil {
		resourceQ = *o.Resource
	}
	if resourceQ != "" {
		qs.Set("resource", resourceQ)
	}

	var slotQ string
	if o.Slot != nil {
		slotQ = *o.Slot
	}
	if slotQ != "" {
		qs.Set("slot", slotQ)
	}

	var stateQ string
	if o.State != nil {
		stateQ = *o.State
	}
	if stateQ != "" {
		qs.Set("state", stateQ)
	}

	var toQ string
	if o.To != nil {
		toQ = o.To.String()
	}
	if toQ != "" {
		qs.Set("to", toQ)
	}

	var userQ string
	if o.User != nil {
		userQ = *o.User
	}
	if userQ != "" {
		qs.Set("user", userQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *QueryBookingRecordsURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *QueryBookingRecordsURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *QueryBookingRecordsURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on QueryBookingRecordsURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on QueryBookingRecordsURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *QueryBookingRecordsURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
