// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// ReplaceBookingOKCode is the HTTP code returned for type ReplaceBookingOK
const ReplaceBookingOKCode int = 200

/*
ReplaceBookingOK OK

swagger:response replaceBookingOK
*/
type ReplaceBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookingEdit `json:"body,omitempty"`
}

// NewReplaceBookingOK creates ReplaceBookingOK with default headers values
func NewReplaceBookingOK() *ReplaceBookingOK {

	return &ReplaceBookingOK{}
}

// WithPayload adds the payload to the replace booking o k response
func (o *ReplaceBookingOK) WithPayload(payload *models.BookingEdit) *ReplaceBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace booking o k response
func (o *ReplaceBookingOK) SetPayload(payload *models.BookingEdit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceBookingUnauthorizedCode is the HTTP code returned for type ReplaceBookingUnauthorized
const ReplaceBookingUnauthorizedCode int = 401

/*
ReplaceBookingUnauthorized Unauthorized

swagger:response replaceBookingUnauthorized
*/
type ReplaceBookingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceBookingUnauthorized creates ReplaceBookingUnauthorized with default headers values
func NewReplaceBookingUnauthorized() *ReplaceBookingUnauthorized {

	return &ReplaceBookingUnauthorized{}
}

// WithPayload adds the payload to the replace booking unauthorized response
func (o *ReplaceBookingUnauthorized) WithPayload(payload *models.Error) *ReplaceBookingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace booking unauthorized response
func (o *ReplaceBookingUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceBookingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceBookingNotFoundCode is the HTTP code returned for type ReplaceBookingNotFound
const ReplaceBookingNotFoundCode int = 404

/*
ReplaceBookingNotFound The specified resource was not found

swagger:response replaceBookingNotFound
*/
type ReplaceBookingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceBookingNotFound creates ReplaceBookingNotFound with default headers values
func NewReplaceBookingNotFound() *ReplaceBookingNotFound {

	return &ReplaceBookingNotFound{}
}

// WithPayload adds the payload to the replace booking not found response
func (o *ReplaceBookingNotFound) WithPayload(payload *models.Error) *ReplaceBookingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace booking not found response
func (o *ReplaceBookingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceBookingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceBookingConflictCode is the HTTP code returned for type ReplaceBookingConflict
const ReplaceBookingConflictCode int = 409

/*
ReplaceBookingConflict The booking was changed, started, or conflicts with the proposed replacement

swagger:response replaceBookingConflict
*/
type ReplaceBookingConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceBookingConflict creates ReplaceBookingConflict with default headers values
func NewReplaceBookingConflict() *ReplaceBookingConflict {

	return &ReplaceBookingConflict{}
}

// WithPayload adds the payload to the replace booking conflict response
func (o *ReplaceBookingConflict) WithPayload(payload *models.Error) *ReplaceBookingConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace booking conflict response
func (o *ReplaceBookingConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceBookingConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceBookingInternalServerErrorCode is the HTTP code returned for type ReplaceBookingInternalServerError
const ReplaceBookingInternalServerErrorCode int = 500

/*
ReplaceBookingInternalServerError Internal Error

swagger:response replaceBookingInternalServerError
*/
type ReplaceBookingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceBookingInternalServerError creates ReplaceBookingInternalServerError with default headers values
func NewReplaceBookingInternalServerError() *ReplaceBookingInternalServerError {

	return &ReplaceBookingInternalServerError{}
}

// WithPayload adds the payload to the replace booking internal server error response
func (o *ReplaceBookingInternalServerError) WithPayload(payload *models.Error) *ReplaceBookingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace booking internal server error response
func (o *ReplaceBookingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceBookingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
