// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/timdrysdale/interval/internal/serve/models"
)

// ReplaceManifestOKCode is the HTTP code returned for type ReplaceManifestOK
const ReplaceManifestOKCode int = 200

/*ReplaceManifestOK OK

swagger:response replaceManifestOK
*/
type ReplaceManifestOK struct {

	/*
	  In: Body
	*/
	Payload *models.StoreStatusAdmin `json:"body,omitempty"`
}

// NewReplaceManifestOK creates ReplaceManifestOK with default headers values
func NewReplaceManifestOK() *ReplaceManifestOK {

	return &ReplaceManifestOK{}
}

// WithPayload adds the payload to the replace manifest o k response
func (o *ReplaceManifestOK) WithPayload(payload *models.StoreStatusAdmin) *ReplaceManifestOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace manifest o k response
func (o *ReplaceManifestOK) SetPayload(payload *models.StoreStatusAdmin) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceManifestOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceManifestUnauthorizedCode is the HTTP code returned for type ReplaceManifestUnauthorized
const ReplaceManifestUnauthorizedCode int = 401

/*ReplaceManifestUnauthorized Unauthorized

swagger:response replaceManifestUnauthorized
*/
type ReplaceManifestUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceManifestUnauthorized creates ReplaceManifestUnauthorized with default headers values
func NewReplaceManifestUnauthorized() *ReplaceManifestUnauthorized {

	return &ReplaceManifestUnauthorized{}
}

// WithPayload adds the payload to the replace manifest unauthorized response
func (o *ReplaceManifestUnauthorized) WithPayload(payload *models.Error) *ReplaceManifestUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace manifest unauthorized response
func (o *ReplaceManifestUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceManifestUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceManifestNotFoundCode is the HTTP code returned for type ReplaceManifestNotFound
const ReplaceManifestNotFoundCode int = 404

/*ReplaceManifestNotFound The specified resource was not found

swagger:response replaceManifestNotFound
*/
type ReplaceManifestNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceManifestNotFound creates ReplaceManifestNotFound with default headers values
func NewReplaceManifestNotFound() *ReplaceManifestNotFound {

	return &ReplaceManifestNotFound{}
}

// WithPayload adds the payload to the replace manifest not found response
func (o *ReplaceManifestNotFound) WithPayload(payload *models.Error) *ReplaceManifestNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace manifest not found response
func (o *ReplaceManifestNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceManifestNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ReplaceManifestInternalServerErrorCode is the HTTP code returned for type ReplaceManifestInternalServerError
const ReplaceManifestInternalServerErrorCode int = 500

/*ReplaceManifestInternalServerError Internal Error

swagger:response replaceManifestInternalServerError
*/
type ReplaceManifestInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewReplaceManifestInternalServerError creates ReplaceManifestInternalServerError with default headers values
func NewReplaceManifestInternalServerError() *ReplaceManifestInternalServerError {

	return &ReplaceManifestInternalServerError{}
}

// WithPayload adds the payload to the replace manifest internal server error response
func (o *ReplaceManifestInternalServerError) WithPayload(payload *models.Error) *ReplaceManifestInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the replace manifest internal server error response
func (o *ReplaceManifestInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ReplaceManifestInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
