// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// RequestResourceReleaseAcceptedCode is the HTTP code returned for type RequestResourceReleaseAccepted
const RequestResourceReleaseAcceptedCode int = 202

/*
RequestResourceReleaseAccepted Verification requested or degraded release recorded

swagger:response requestResourceReleaseAccepted
*/
type RequestResourceReleaseAccepted struct {

	/*
	  In: Body
	*/
	Payload *models.ResourceReleaseState `json:"body,omitempty"`
}

// NewRequestResourceReleaseAccepted creates RequestResourceReleaseAccepted with default headers values
func NewRequestResourceReleaseAccepted() *RequestResourceReleaseAccepted {

	return &RequestResourceReleaseAccepted{}
}

// WithPayload adds the payload to the request resource release accepted response
func (o *RequestResourceReleaseAccepted) WithPayload(payload *models.ResourceReleaseState) *RequestResourceReleaseAccepted {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request resource release accepted response
func (o *RequestResourceReleaseAccepted) SetPayload(payload *models.ResourceReleaseState) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestResourceReleaseAccepted) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(202)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RequestResourceReleaseUnauthorizedCode is the HTTP code returned for type RequestResourceReleaseUnauthorized
const RequestResourceReleaseUnauthorizedCode int = 401

/*
RequestResourceReleaseUnauthorized Unauthorized

swagger:response requestResourceReleaseUnauthorized
*/
type RequestResourceReleaseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestResourceReleaseUnauthorized creates RequestResourceReleaseUnauthorized with default headers values
func NewRequestResourceReleaseUnauthorized() *RequestResourceReleaseUnauthorized {

	return &RequestResourceReleaseUnauthorized{}
}

// WithPayload adds the payload to the request resource release unauthorized response
func (o *RequestResourceReleaseUnauthorized) WithPayload(payload *models.Error) *RequestResourceReleaseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request resource release unauthorized response
func (o *RequestResourceReleaseUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestResourceReleaseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RequestResourceReleaseNotFoundCode is the HTTP code returned for type RequestResourceReleaseNotFound
const RequestResourceReleaseNotFoundCode int = 404

/*
RequestResourceReleaseNotFound The specified resource was not found

swagger:response requestResourceReleaseNotFound
*/
type RequestResourceReleaseNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestResourceReleaseNotFound creates RequestResourceReleaseNotFound with default headers values
func NewRequestResourceReleaseNotFound() *RequestResourceReleaseNotFound {

	return &RequestResourceReleaseNotFound{}
}

// WithPayload adds the payload to the request resource release not found response
func (o *RequestResourceReleaseNotFound) WithPayload(payload *models.Error) *RequestResourceReleaseNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request resource release not found response
func (o *RequestResourceReleaseNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestResourceReleaseNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RequestResourceReleaseConflictCode is the HTTP code returned for type RequestResourceReleaseConflict
const RequestResourceReleaseConflictCode int = 409

/*
RequestResourceReleaseConflict The booking was changed, started, or conflicts with the proposed replacement

swagger:response requestResourceReleaseConflict
*/
type RequestResourceReleaseConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestResourceReleaseConflict creates RequestResourceReleaseConflict with default headers values
func NewRequestResourceReleaseConflict() *RequestResourceReleaseConflict {

	return &RequestResourceReleaseConflict{}
}

// WithPayload adds the payload to the request resource release conflict response
func (o *RequestResourceReleaseConflict) WithPayload(payload *models.Error) *RequestResourceReleaseConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request resource release conflict response
func (o *RequestResourceReleaseConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestResourceReleaseConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RequestResourceReleaseInternalServerErrorCode is the HTTP code returned for type RequestResourceReleaseInternalServerError
const RequestResourceReleaseInternalServerErrorCode int = 500

/*
RequestResourceReleaseInternalServerError Internal Error

swagger:response requestResourceReleaseInternalServerError
*/
type RequestResourceReleaseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRequestResourceReleaseInternalServerError creates RequestResourceReleaseInternalServerError with default headers values
func NewRequestResourceReleaseInternalServerError() *RequestResourceReleaseInternalServerError {

	return &RequestResourceReleaseInternalServerError{}
}

// WithPayload adds the payload to the request resource release internal server error response
func (o *RequestResourceReleaseInternalServerError) WithPayload(payload *models.Error) *RequestResourceReleaseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the request resource release internal server error response
func (o *RequestResourceReleaseInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RequestResourceReleaseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
