// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewRequestResourceReleaseParams creates a new RequestResourceReleaseParams object
//
// There are no default values defined in the spec.
func NewRequestResourceReleaseParams() RequestResourceReleaseParams {

	return RequestResourceReleaseParams{}
}

// RequestResourceReleaseParams contains all the bound params for the request resource release operation
// typically these are obtained from a http.Request
//
// swagger:parameters RequestResourceRelease
type RequestResourceReleaseParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  In: query
	*/
	OverrideReason *string
	/*
	  Required: true
	  In: path
	*/
	ResourceName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRequestResourceReleaseParams() beforehand.
func (o *RequestResourceReleaseParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qOverrideReason, qhkOverrideReason, _ := qs.GetOK("override_reason")
	if err := o.bindOverrideReason(qOverrideReason, qhkOverrideReason, route.Formats); err != nil {
		res = append(res, err)
	}

	rResourceName, rhkResourceName, _ := route.Params.GetOK("resource_name")
	if err := o.bindResourceName(rResourceName, rhkResourceName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindOverrideReason binds and validates parameter OverrideReason from query.
func (o *RequestResourceReleaseParams) bindOverrideReason(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.OverrideReason = &raw

	return nil
}

// bindResourceName binds and validates parameter ResourceName from path.
func (o *RequestResourceReleaseParams) bindResourceName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.ResourceName = raw

	return nil
}
