// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// ResolveOperationalAlertOKCode is the HTTP code returned for type ResolveOperationalAlertOK
const ResolveOperationalAlertOKCode int = 200

/*
ResolveOperationalAlertOK OK

swagger:response resolveOperationalAlertOK
*/
type ResolveOperationalAlertOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationalAlert `json:"body,omitempty"`
}

// NewResolveOperationalAlertOK creates ResolveOperationalAlertOK with default headers values
func NewResolveOperationalAlertOK() *ResolveOperationalAlertOK {

	return &ResolveOperationalAlertOK{}
}

// WithPayload adds the payload to the resolve operational alert o k response
func (o *ResolveOperationalAlertOK) WithPayload(payload *models.OperationalAlert) *ResolveOperationalAlertOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resolve operational alert o k response
func (o *ResolveOperationalAlertOK) SetPayload(payload *models.OperationalAlert) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResolveOperationalAlertOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ResolveOperationalAlertUnauthorizedCode is the HTTP code returned for type ResolveOperationalAlertUnauthorized
const ResolveOperationalAlertUnauthorizedCode int = 401

/*
ResolveOperationalAlertUnauthorized Unauthorized

swagger:response resolveOperationalAlertUnauthorized
*/
type ResolveOperationalAlertUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewResolveOperationalAlertUnauthorized creates ResolveOperationalAlertUnauthorized with default headers values
func NewResolveOperationalAlertUnauthorized() *ResolveOperationalAlertUnauthorized {

	return &ResolveOperationalAlertUnauthorized{}
}

// WithPayload adds the payload to the resolve operational alert unauthorized response
func (o *ResolveOperationalAlertUnauthorized) WithPayload(payload *models.Error) *ResolveOperationalAlertUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resolve operational alert unauthorized response
func (o *ResolveOperationalAlertUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResolveOperationalAlertUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ResolveOperationalAlertNotFoundCode is the HTTP code returned for type ResolveOperationalAlertNotFound
const ResolveOperationalAlertNotFoundCode int = 404

/*
ResolveOperationalAlertNotFound The specified resource was not found

swagger:response resolveOperationalAlertNotFound
*/
type ResolveOperationalAlertNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewResolveOperationalAlertNotFound creates ResolveOperationalAlertNotFound with default headers values
func NewResolveOperationalAlertNotFound() *ResolveOperationalAlertNotFound {

	return &ResolveOperationalAlertNotFound{}
}

// WithPayload adds the payload to the resolve operational alert not found response
func (o *ResolveOperationalAlertNotFound) WithPayload(payload *models.Error) *ResolveOperationalAlertNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resolve operational alert not found response
func (o *ResolveOperationalAlertNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResolveOperationalAlertNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// ResolveOperationalAlertInternalServerErrorCode is the HTTP code returned for type ResolveOperationalAlertInternalServerError
const ResolveOperationalAlertInternalServerErrorCode int = 500

/*
ResolveOperationalAlertInternalServerError Internal Error

swagger:response resolveOperationalAlertInternalServerError
*/
type ResolveOperationalAlertInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewResolveOperationalAlertInternalServerError creates ResolveOperationalAlertInternalServerError with default headers values
func NewResolveOperationalAlertInternalServerError() *ResolveOperationalAlertInternalServerError {

	return &ResolveOperationalAlertInternalServerError{}
}

// WithPayload adds the payload to the resolve operational alert internal server error response
func (o *ResolveOperationalAlertInternalServerError) WithPayload(payload *models.Error) *ResolveOperationalAlertInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the resolve operational alert internal server error response
func (o *ResolveOperationalAlertInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ResolveOperationalAlertInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
