// Package pretty is a test for the patch to client/models
// that adds a stringifier so that error codes printed
// nicely when using the client (e.g. from command line)
// else one just gets pointer values rather than the text
// sent from the server
// Note that this package does not do the actual prettifying
// That is done by the file in ${repo}/patch/internal/client/models/pretty.go
// which is based on the code in this file, but altered to work with the
// autogenerated code. This is a separate package used to develop that patch.

package pretty

import (
	"fmt"
)

type PointyError struct {
	Code    *string
	Message *string
}

func (e PointyError) String() string {
	code := ""
	message := ""
	if e.Code != nil {
		code = *(e.Code)
	}
	if e.Message != nil {
		message = *(e.Message)
	}
	return fmt.Sprintf(`{"Code":%#v,"Message":%#v}`, code, message)
}
