// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OperationalOccurrence operational occurrence
//
// swagger:model OperationalOccurrence
type OperationalOccurrence struct {

	// booking name
	BookingName string `json:"booking_name,omitempty"`

	// detail
	Detail string `json:"detail,omitempty"`

	// job id
	JobID string `json:"job_id,omitempty"`

	// manifest version
	// Required: true
	ManifestVersion *int64 `json:"manifest_version"`

	// occurrence at
	// Required: true
	// Format: date-time
	OccurrenceAt *strfmt.DateTime `json:"occurrence_at"`

	// resource
	// Required: true
	Resource *string `json:"resource"`

	// schedule
	// Required: true
	Schedule *string `json:"schedule"`

	// slot
	// Required: true
	Slot *string `json:"slot"`

	// state
	// Required: true
	// Enum: ["planned","skipped","conflict","missed"]
	State *string `json:"state"`

	// workflow
	// Required: true
	Workflow *string `json:"workflow"`
}

// Validate validates this operational occurrence
func (m *OperationalOccurrence) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateManifestVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOccurrenceAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSchedule(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSlot(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkflow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationalOccurrence) validateManifestVersion(formats strfmt.Registry) error {

	if err := validate.Required("manifest_version", "body", m.ManifestVersion); err != nil {
		return err
	}

	return nil
}

func (m *OperationalOccurrence) validateOccurrenceAt(formats strfmt.Registry) error {

	if err := validate.Required("occurrence_at", "body", m.OccurrenceAt); err != nil {
		return err
	}

	if err := validate.FormatOf("occurrence_at", "body", "date-time", m.OccurrenceAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *OperationalOccurrence) validateResource(formats strfmt.Registry) error {

	if err := validate.Required("resource", "body", m.Resource); err != nil {
		return err
	}

	return nil
}

func (m *OperationalOccurrence) validateSchedule(formats strfmt.Registry) error {

	if err := validate.Required("schedule", "body", m.Schedule); err != nil {
		return err
	}

	return nil
}

func (m *OperationalOccurrence) validateSlot(formats strfmt.Registry) error {

	if err := validate.Required("slot", "body", m.Slot); err != nil {
		return err
	}

	return nil
}

var operationalOccurrenceTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["planned","skipped","conflict","missed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationalOccurrenceTypeStatePropEnum = append(operationalOccurrenceTypeStatePropEnum, v)
	}
}

const (

	// OperationalOccurrenceStatePlanned captures enum value "planned"
	OperationalOccurrenceStatePlanned string = "planned"

	// OperationalOccurrenceStateSkipped captures enum value "skipped"
	OperationalOccurrenceStateSkipped string = "skipped"

	// OperationalOccurrenceStateConflict captures enum value "conflict"
	OperationalOccurrenceStateConflict string = "conflict"

	// OperationalOccurrenceStateMissed captures enum value "missed"
	OperationalOccurrenceStateMissed string = "missed"
)

// prop value enum
func (m *OperationalOccurrence) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, operationalOccurrenceTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *OperationalOccurrence) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	// value enum
	if err := m.validateStateEnum("state", "body", *m.State); err != nil {
		return err
	}

	return nil
}

func (m *OperationalOccurrence) validateWorkflow(formats strfmt.Registry) error {

	if err := validate.Required("workflow", "body", m.Workflow); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this operational occurrence based on context it is used
func (m *OperationalOccurrence) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationalOccurrence) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationalOccurrence) UnmarshalBinary(b []byte) error {
	var res OperationalOccurrence
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
