// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OperationalPipelineStage operational pipeline stage
//
// swagger:model OperationalPipelineStage
type OperationalPipelineStage struct {

	// job template
	// Required: true
	JobTemplate *string `json:"job_template"`

	// name
	// Required: true
	Name *string `json:"name"`

	// wait after
	WaitAfter string `json:"wait_after,omitempty"`
}

// Validate validates this operational pipeline stage
func (m *OperationalPipelineStage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJobTemplate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationalPipelineStage) validateJobTemplate(formats strfmt.Registry) error {

	if err := validate.Required("job_template", "body", m.JobTemplate); err != nil {
		return err
	}

	return nil
}

func (m *OperationalPipelineStage) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this operational pipeline stage based on context it is used
func (m *OperationalPipelineStage) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationalPipelineStage) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationalPipelineStage) UnmarshalBinary(b []byte) error {
	var res OperationalPipelineStage
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
