// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Stream stream
//
// Represents an assigned, valid booking slot for an individual piece of equipment
// Example: {"for":"video","token":"ey....","url":"https://relay-access.practable.io/session/abc123"}
//
// swagger:model Stream
type Stream struct {

	// audience
	// Required: true
	Audience *string `json:"audience"`

	// connection type
	// Required: true
	ConnectionType *string `json:"connection_type"`

	// Describes the stream, and doubles as template key in the URL
	// Example: video
	// Required: true
	For *string `json:"for"`

	// scopes
	// Required: true
	Scopes []string `json:"scopes"`

	// topic
	// Required: true
	Topic *string `json:"topic"`

	// URL at which to obtain access to the stream (getting a redirect URL containing a one time code)
	// Example: https://relay-access.practable.io/session/abc123
	// Required: true
	URL *string `json:"url"`
}

// Validate validates this stream
func (m *Stream) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAudience(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConnectionType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateScopes(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTopic(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Stream) validateAudience(formats strfmt.Registry) error {

	if err := validate.Required("audience", "body", m.Audience); err != nil {
		return err
	}

	return nil
}

func (m *Stream) validateConnectionType(formats strfmt.Registry) error {

	if err := validate.Required("connection_type", "body", m.ConnectionType); err != nil {
		return err
	}

	return nil
}

func (m *Stream) validateFor(formats strfmt.Registry) error {

	if err := validate.Required("for", "body", m.For); err != nil {
		return err
	}

	return nil
}

func (m *Stream) validateScopes(formats strfmt.Registry) error {

	if err := validate.Required("scopes", "body", m.Scopes); err != nil {
		return err
	}

	return nil
}

func (m *Stream) validateTopic(formats strfmt.Registry) error {

	if err := validate.Required("topic", "body", m.Topic); err != nil {
		return err
	}

	return nil
}

func (m *Stream) validateURL(formats strfmt.Registry) error {

	if err := validate.Required("url", "body", m.URL); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this stream based on context it is used
func (m *Stream) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Stream) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Stream) UnmarshalBinary(b []byte) error {
	var res Stream
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
