// Code generated by go-swagger; DO NOT EDIT.

package operationsops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/practable/book/internal/serve/models"
)

// NewActivateOperationalJobParams creates a new ActivateOperationalJobParams object
//
// There are no default values defined in the spec.
func NewActivateOperationalJobParams() ActivateOperationalJobParams {

	return ActivateOperationalJobParams{}
}

// ActivateOperationalJobParams contains all the bound params for the activate operational job operation
// typically these are obtained from a http.Request
//
// swagger:parameters ActivateOperationalJob
type ActivateOperationalJobParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: header
	*/
	XBookDeliveryID string
	/*
	  Required: true
	  In: header
	*/
	XBookDirection string
	/*
	  Required: true
	  In: header
	*/
	XBookSignature string
	/*
	  Required: true
	  In: header
	*/
	XBookTimestamp string
	/*
	  Required: true
	  In: body
	*/
	Activation *models.OperationalJobActivation
	/*
	  Required: true
	  In: path
	*/
	JobID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewActivateOperationalJobParams() beforehand.
func (o *ActivateOperationalJobParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindXBookDeliveryID(r.Header[http.CanonicalHeaderKey("X-Book-Delivery-ID")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXBookDirection(r.Header[http.CanonicalHeaderKey("X-Book-Direction")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXBookSignature(r.Header[http.CanonicalHeaderKey("X-Book-Signature")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if err := o.bindXBookTimestamp(r.Header[http.CanonicalHeaderKey("X-Book-Timestamp")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.OperationalJobActivation
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("activation", "body", ""))
			} else {
				res = append(res, errors.NewParseError("activation", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Activation = &body
			}
		}
	} else {
		res = append(res, errors.Required("activation", "body", ""))
	}

	rJobID, rhkJobID, _ := route.Params.GetOK("job_id")
	if err := o.bindJobID(rJobID, rhkJobID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindXBookDeliveryID binds and validates parameter XBookDeliveryID from header.
func (o *ActivateOperationalJobParams) bindXBookDeliveryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("X-Book-Delivery-ID", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("X-Book-Delivery-ID", "header", raw); err != nil {
		return err
	}
	o.XBookDeliveryID = raw

	return nil
}

// bindXBookDirection binds and validates parameter XBookDirection from header.
func (o *ActivateOperationalJobParams) bindXBookDirection(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("X-Book-Direction", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("X-Book-Direction", "header", raw); err != nil {
		return err
	}
	o.XBookDirection = raw

	if err := o.validateXBookDirection(formats); err != nil {
		return err
	}

	return nil
}

// validateXBookDirection carries on validations for parameter XBookDirection
func (o *ActivateOperationalJobParams) validateXBookDirection(formats strfmt.Registry) error {

	if err := validate.EnumCase("X-Book-Direction", "header", o.XBookDirection, []interface{}{"runner-to-book"}, true); err != nil {
		return err
	}

	return nil
}

// bindXBookSignature binds and validates parameter XBookSignature from header.
func (o *ActivateOperationalJobParams) bindXBookSignature(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("X-Book-Signature", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("X-Book-Signature", "header", raw); err != nil {
		return err
	}
	o.XBookSignature = raw

	return nil
}

// bindXBookTimestamp binds and validates parameter XBookTimestamp from header.
func (o *ActivateOperationalJobParams) bindXBookTimestamp(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("X-Book-Timestamp", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("X-Book-Timestamp", "header", raw); err != nil {
		return err
	}
	o.XBookTimestamp = raw

	return nil
}

// bindJobID binds and validates parameter JobID from path.
func (o *ActivateOperationalJobParams) bindJobID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.JobID = raw

	return nil
}
