// Code generated by go-swagger; DO NOT EDIT.

package policies

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAvailabilityHandlerFunc turns a function with the right signature into a get availability handler
type GetAvailabilityHandlerFunc func(GetAvailabilityParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAvailabilityHandlerFunc) Handle(params GetAvailabilityParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAvailabilityHandler interface for that can handle valid get availability params
type GetAvailabilityHandler interface {
	Handle(GetAvailabilityParams, interface{}) middleware.Responder
}

// NewGetAvailability creates a new http.Handler for the get availability operation
func NewGetAvailability(ctx *middleware.Context, handler GetAvailabilityHandler) *GetAvailability {
	return &GetAvailability{Context: ctx, Handler: handler}
}

/* GetAvailability swagger:route GET /policies/{policy_name}/slots/{slot_name} policies getAvailability

Get availability for the slot under the policy

TODO pagination

*/
type GetAvailability struct {
	Context *middleware.Context
	Handler GetAvailabilityHandler
}

func (o *GetAvailability) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAvailabilityParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
