// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BookingActivation booking activation
//
// swagger:model BookingActivation
type BookingActivation struct {

	// booking name
	// Required: true
	BookingName *string `json:"booking_name"`

	// cleanup stages
	CleanupStages []*BookingActivationStage `json:"cleanup_stages"`

	// cleanup state
	// Required: true
	// Enum: ["not_required","pending","running","succeeded","failed"]
	CleanupState *string `json:"cleanup_state"`

	// current stage
	// Required: true
	// Minimum: 0
	CurrentStage *int64 `json:"current_stage"`

	// failure code
	FailureCode string `json:"failure_code,omitempty"`

	// failure guidance
	FailureGuidance *OperationalFailureGuidance `json:"failure_guidance,omitempty"`

	// failure message
	FailureMessage string `json:"failure_message,omitempty"`

	// id
	// Required: true
	ID *string `json:"id"`

	// maximum recovery attempts
	// Maximum: 5
	// Minimum: 0
	MaximumRecoveryAttempts *int64 `json:"maximum_recovery_attempts,omitempty"`

	// progress message
	// Required: true
	ProgressMessage *string `json:"progress_message"`

	// recovery attempt
	// Minimum: 0
	RecoveryAttempt *int64 `json:"recovery_attempt,omitempty"`

	// recovery stages
	RecoveryStages []*BookingActivationStage `json:"recovery_stages"`

	// stages
	// Required: true
	Stages []*BookingActivationStage `json:"stages"`

	// state
	// Required: true
	// Enum: ["preparing","active","failed","cancelled","expired","cleaning","closed","cleanup_failed"]
	State *string `json:"state"`

	// stream
	// Required: true
	Stream *string `json:"stream"`
}

// Validate validates this booking activation
func (m *BookingActivation) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBookingName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCleanupStages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCleanupState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCurrentStage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFailureGuidance(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaximumRecoveryAttempts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProgressMessage(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecoveryAttempt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRecoveryStages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStages(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStream(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BookingActivation) validateBookingName(formats strfmt.Registry) error {

	if err := validate.Required("booking_name", "body", m.BookingName); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateCleanupStages(formats strfmt.Registry) error {
	if swag.IsZero(m.CleanupStages) { // not required
		return nil
	}

	for i := 0; i < len(m.CleanupStages); i++ {
		if swag.IsZero(m.CleanupStages[i]) { // not required
			continue
		}

		if m.CleanupStages[i] != nil {
			if err := m.CleanupStages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cleanup_stages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cleanup_stages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var bookingActivationTypeCleanupStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["not_required","pending","running","succeeded","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		bookingActivationTypeCleanupStatePropEnum = append(bookingActivationTypeCleanupStatePropEnum, v)
	}
}

const (

	// BookingActivationCleanupStateNotRequired captures enum value "not_required"
	BookingActivationCleanupStateNotRequired string = "not_required"

	// BookingActivationCleanupStatePending captures enum value "pending"
	BookingActivationCleanupStatePending string = "pending"

	// BookingActivationCleanupStateRunning captures enum value "running"
	BookingActivationCleanupStateRunning string = "running"

	// BookingActivationCleanupStateSucceeded captures enum value "succeeded"
	BookingActivationCleanupStateSucceeded string = "succeeded"

	// BookingActivationCleanupStateFailed captures enum value "failed"
	BookingActivationCleanupStateFailed string = "failed"
)

// prop value enum
func (m *BookingActivation) validateCleanupStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, bookingActivationTypeCleanupStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BookingActivation) validateCleanupState(formats strfmt.Registry) error {

	if err := validate.Required("cleanup_state", "body", m.CleanupState); err != nil {
		return err
	}

	// value enum
	if err := m.validateCleanupStateEnum("cleanup_state", "body", *m.CleanupState); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateCurrentStage(formats strfmt.Registry) error {

	if err := validate.Required("current_stage", "body", m.CurrentStage); err != nil {
		return err
	}

	if err := validate.MinimumInt("current_stage", "body", *m.CurrentStage, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateFailureGuidance(formats strfmt.Registry) error {
	if swag.IsZero(m.FailureGuidance) { // not required
		return nil
	}

	if m.FailureGuidance != nil {
		if err := m.FailureGuidance.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("failure_guidance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("failure_guidance")
			}
			return err
		}
	}

	return nil
}

func (m *BookingActivation) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateMaximumRecoveryAttempts(formats strfmt.Registry) error {
	if swag.IsZero(m.MaximumRecoveryAttempts) { // not required
		return nil
	}

	if err := validate.MinimumInt("maximum_recovery_attempts", "body", *m.MaximumRecoveryAttempts, 0, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("maximum_recovery_attempts", "body", *m.MaximumRecoveryAttempts, 5, false); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateProgressMessage(formats strfmt.Registry) error {

	if err := validate.Required("progress_message", "body", m.ProgressMessage); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateRecoveryAttempt(formats strfmt.Registry) error {
	if swag.IsZero(m.RecoveryAttempt) { // not required
		return nil
	}

	if err := validate.MinimumInt("recovery_attempt", "body", *m.RecoveryAttempt, 0, false); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateRecoveryStages(formats strfmt.Registry) error {
	if swag.IsZero(m.RecoveryStages) { // not required
		return nil
	}

	for i := 0; i < len(m.RecoveryStages); i++ {
		if swag.IsZero(m.RecoveryStages[i]) { // not required
			continue
		}

		if m.RecoveryStages[i] != nil {
			if err := m.RecoveryStages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recovery_stages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recovery_stages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BookingActivation) validateStages(formats strfmt.Registry) error {

	if err := validate.Required("stages", "body", m.Stages); err != nil {
		return err
	}

	for i := 0; i < len(m.Stages); i++ {
		if swag.IsZero(m.Stages[i]) { // not required
			continue
		}

		if m.Stages[i] != nil {
			if err := m.Stages[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

var bookingActivationTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["preparing","active","failed","cancelled","expired","cleaning","closed","cleanup_failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		bookingActivationTypeStatePropEnum = append(bookingActivationTypeStatePropEnum, v)
	}
}

const (

	// BookingActivationStatePreparing captures enum value "preparing"
	BookingActivationStatePreparing string = "preparing"

	// BookingActivationStateActive captures enum value "active"
	BookingActivationStateActive string = "active"

	// BookingActivationStateFailed captures enum value "failed"
	BookingActivationStateFailed string = "failed"

	// BookingActivationStateCancelled captures enum value "cancelled"
	BookingActivationStateCancelled string = "cancelled"

	// BookingActivationStateExpired captures enum value "expired"
	BookingActivationStateExpired string = "expired"

	// BookingActivationStateCleaning captures enum value "cleaning"
	BookingActivationStateCleaning string = "cleaning"

	// BookingActivationStateClosed captures enum value "closed"
	BookingActivationStateClosed string = "closed"

	// BookingActivationStateCleanupFailed captures enum value "cleanup_failed"
	BookingActivationStateCleanupFailed string = "cleanup_failed"
)

// prop value enum
func (m *BookingActivation) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, bookingActivationTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *BookingActivation) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	// value enum
	if err := m.validateStateEnum("state", "body", *m.State); err != nil {
		return err
	}

	return nil
}

func (m *BookingActivation) validateStream(formats strfmt.Registry) error {

	if err := validate.Required("stream", "body", m.Stream); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this booking activation based on the context it is used
func (m *BookingActivation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCleanupStages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFailureGuidance(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateRecoveryStages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStages(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *BookingActivation) contextValidateCleanupStages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.CleanupStages); i++ {

		if m.CleanupStages[i] != nil {

			if swag.IsZero(m.CleanupStages[i]) { // not required
				return nil
			}

			if err := m.CleanupStages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("cleanup_stages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("cleanup_stages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BookingActivation) contextValidateFailureGuidance(ctx context.Context, formats strfmt.Registry) error {

	if m.FailureGuidance != nil {

		if swag.IsZero(m.FailureGuidance) { // not required
			return nil
		}

		if err := m.FailureGuidance.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("failure_guidance")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("failure_guidance")
			}
			return err
		}
	}

	return nil
}

func (m *BookingActivation) contextValidateRecoveryStages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.RecoveryStages); i++ {

		if m.RecoveryStages[i] != nil {

			if swag.IsZero(m.RecoveryStages[i]) { // not required
				return nil
			}

			if err := m.RecoveryStages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("recovery_stages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("recovery_stages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *BookingActivation) contextValidateStages(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Stages); i++ {

		if m.Stages[i] != nil {

			if swag.IsZero(m.Stages[i]) { // not required
				return nil
			}

			if err := m.Stages[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("stages" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("stages" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *BookingActivation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BookingActivation) UnmarshalBinary(b []byte) error {
	var res BookingActivation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
