// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// OperationalFailureAction operational failure action
//
// swagger:model OperationalFailureAction
type OperationalFailureAction struct {

	// label
	// Required: true
	Label *string `json:"label"`

	// type
	// Required: true
	// Enum: ["retry","choose_another","contact_support"]
	Type *string `json:"type"`

	// url
	URL string `json:"url,omitempty"`
}

// Validate validates this operational failure action
func (m *OperationalFailureAction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLabel(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateType(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *OperationalFailureAction) validateLabel(formats strfmt.Registry) error {

	if err := validate.Required("label", "body", m.Label); err != nil {
		return err
	}

	return nil
}

var operationalFailureActionTypeTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["retry","choose_another","contact_support"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		operationalFailureActionTypeTypePropEnum = append(operationalFailureActionTypeTypePropEnum, v)
	}
}

const (

	// OperationalFailureActionTypeRetry captures enum value "retry"
	OperationalFailureActionTypeRetry string = "retry"

	// OperationalFailureActionTypeChooseAnother captures enum value "choose_another"
	OperationalFailureActionTypeChooseAnother string = "choose_another"

	// OperationalFailureActionTypeContactSupport captures enum value "contact_support"
	OperationalFailureActionTypeContactSupport string = "contact_support"
)

// prop value enum
func (m *OperationalFailureAction) validateTypeEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, operationalFailureActionTypeTypePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *OperationalFailureAction) validateType(formats strfmt.Registry) error {

	if err := validate.Required("type", "body", m.Type); err != nil {
		return err
	}

	// value enum
	if err := m.validateTypeEnum("type", "body", *m.Type); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this operational failure action based on context it is used
func (m *OperationalFailureAction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationalFailureAction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationalFailureAction) UnmarshalBinary(b []byte) error {
	var res OperationalFailureAction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
