// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// OperationalProgressMessages operational progress messages
//
// swagger:model OperationalProgressMessages
type OperationalProgressMessages struct {

	// initial
	Initial string `json:"initial,omitempty"`

	// retry
	Retry string `json:"retry,omitempty"`
}

// Validate validates this operational progress messages
func (m *OperationalProgressMessages) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this operational progress messages based on context it is used
func (m *OperationalProgressMessages) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *OperationalProgressMessages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *OperationalProgressMessages) UnmarshalBinary(b []byte) error {
	var res OperationalProgressMessages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
