// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ResourceReleaseState resource release state
//
// swagger:model ResourceReleaseState
type ResourceReleaseState struct {

	// failing streams
	// Required: true
	FailingStreams []string `json:"failing_streams"`

	// manifest version
	// Required: true
	ManifestVersion *int64 `json:"manifest_version"`

	// override reason
	// Required: true
	OverrideReason *string `json:"override_reason"`

	// released at
	// Format: date-time
	ReleasedAt strfmt.DateTime `json:"released_at,omitempty"`

	// requested at
	// Required: true
	// Format: date-time
	RequestedAt *strfmt.DateTime `json:"requested_at"`

	// requested by
	// Required: true
	RequestedBy *string `json:"requested_by"`

	// required streams
	// Required: true
	RequiredStreams []string `json:"required_streams"`

	// resource
	// Required: true
	Resource *string `json:"resource"`

	// state
	// Required: true
	// Enum: ["pending_checks","verified","degraded_override"]
	State *string `json:"state"`
}

// Validate validates this resource release state
func (m *ResourceReleaseState) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateFailingStreams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateManifestVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOverrideReason(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateReleasedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequestedBy(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRequiredStreams(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResource(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ResourceReleaseState) validateFailingStreams(formats strfmt.Registry) error {

	if err := validate.Required("failing_streams", "body", m.FailingStreams); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateManifestVersion(formats strfmt.Registry) error {

	if err := validate.Required("manifest_version", "body", m.ManifestVersion); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateOverrideReason(formats strfmt.Registry) error {

	if err := validate.Required("override_reason", "body", m.OverrideReason); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateReleasedAt(formats strfmt.Registry) error {
	if swag.IsZero(m.ReleasedAt) { // not required
		return nil
	}

	if err := validate.FormatOf("released_at", "body", "date-time", m.ReleasedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateRequestedAt(formats strfmt.Registry) error {

	if err := validate.Required("requested_at", "body", m.RequestedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("requested_at", "body", "date-time", m.RequestedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateRequestedBy(formats strfmt.Registry) error {

	if err := validate.Required("requested_by", "body", m.RequestedBy); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateRequiredStreams(formats strfmt.Registry) error {

	if err := validate.Required("required_streams", "body", m.RequiredStreams); err != nil {
		return err
	}

	return nil
}

func (m *ResourceReleaseState) validateResource(formats strfmt.Registry) error {

	if err := validate.Required("resource", "body", m.Resource); err != nil {
		return err
	}

	return nil
}

var resourceReleaseStateTypeStatePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["pending_checks","verified","degraded_override"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		resourceReleaseStateTypeStatePropEnum = append(resourceReleaseStateTypeStatePropEnum, v)
	}
}

const (

	// ResourceReleaseStateStatePendingChecks captures enum value "pending_checks"
	ResourceReleaseStateStatePendingChecks string = "pending_checks"

	// ResourceReleaseStateStateVerified captures enum value "verified"
	ResourceReleaseStateStateVerified string = "verified"

	// ResourceReleaseStateStateDegradedOverride captures enum value "degraded_override"
	ResourceReleaseStateStateDegradedOverride string = "degraded_override"
)

// prop value enum
func (m *ResourceReleaseState) validateStateEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, resourceReleaseStateTypeStatePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *ResourceReleaseState) validateState(formats strfmt.Registry) error {

	if err := validate.Required("state", "body", m.State); err != nil {
		return err
	}

	// value enum
	if err := m.validateStateEnum("state", "body", *m.State); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this resource release state based on context it is used
func (m *ResourceReleaseState) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ResourceReleaseState) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ResourceReleaseState) UnmarshalBinary(b []byte) error {
	var res ResourceReleaseState
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
