// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetDescriptionParams creates a new GetDescriptionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetDescriptionParams() *GetDescriptionParams {
	return &GetDescriptionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetDescriptionParamsWithTimeout creates a new GetDescriptionParams object
// with the ability to set a timeout on a request.
func NewGetDescriptionParamsWithTimeout(timeout time.Duration) *GetDescriptionParams {
	return &GetDescriptionParams{
		timeout: timeout,
	}
}

// NewGetDescriptionParamsWithContext creates a new GetDescriptionParams object
// with the ability to set a context for a request.
func NewGetDescriptionParamsWithContext(ctx context.Context) *GetDescriptionParams {
	return &GetDescriptionParams{
		Context: ctx,
	}
}

// NewGetDescriptionParamsWithHTTPClient creates a new GetDescriptionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetDescriptionParamsWithHTTPClient(client *http.Client) *GetDescriptionParams {
	return &GetDescriptionParams{
		HTTPClient: client,
	}
}

/*
GetDescriptionParams contains all the parameters to send to the API endpoint

	for the get description operation.

	Typically these are written to a http.Request.
*/
type GetDescriptionParams struct {

	// DescriptionName.
	DescriptionName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDescriptionParams) WithDefaults() *GetDescriptionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get description params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetDescriptionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get description params
func (o *GetDescriptionParams) WithTimeout(timeout time.Duration) *GetDescriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get description params
func (o *GetDescriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get description params
func (o *GetDescriptionParams) WithContext(ctx context.Context) *GetDescriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get description params
func (o *GetDescriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get description params
func (o *GetDescriptionParams) WithHTTPClient(client *http.Client) *GetDescriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get description params
func (o *GetDescriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDescriptionName adds the descriptionName to the get description params
func (o *GetDescriptionParams) WithDescriptionName(descriptionName string) *GetDescriptionParams {
	o.SetDescriptionName(descriptionName)
	return o
}

// SetDescriptionName adds the descriptionName to the get description params
func (o *GetDescriptionParams) SetDescriptionName(descriptionName string) {
	o.DescriptionName = descriptionName
}

// WriteToRequest writes these params to a swagger request
func (o *GetDescriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param description_name
	if err := r.SetPathParam("description_name", o.DescriptionName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
