// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/timdrysdale/interval/internal/client/models"
)

// GetBookingsForUserReader is a Reader for the GetBookingsForUser structure.
type GetBookingsForUserReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetBookingsForUserReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetBookingsForUserOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGetBookingsForUserUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetBookingsForUserNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetBookingsForUserInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetBookingsForUserOK creates a GetBookingsForUserOK with default headers values
func NewGetBookingsForUserOK() *GetBookingsForUserOK {
	return &GetBookingsForUserOK{}
}

/*
GetBookingsForUserOK describes a response with status code 200, with default header values.

OK
*/
type GetBookingsForUserOK struct {
	Payload models.Bookings
}

// IsSuccess returns true when this get bookings for user o k response has a 2xx status code
func (o *GetBookingsForUserOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get bookings for user o k response has a 3xx status code
func (o *GetBookingsForUserOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bookings for user o k response has a 4xx status code
func (o *GetBookingsForUserOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get bookings for user o k response has a 5xx status code
func (o *GetBookingsForUserOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get bookings for user o k response a status code equal to that given
func (o *GetBookingsForUserOK) IsCode(code int) bool {
	return code == 200
}

func (o *GetBookingsForUserOK) Error() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserOK  %+v", 200, o.Payload)
}

func (o *GetBookingsForUserOK) String() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserOK  %+v", 200, o.Payload)
}

func (o *GetBookingsForUserOK) GetPayload() models.Bookings {
	return o.Payload
}

func (o *GetBookingsForUserOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBookingsForUserUnauthorized creates a GetBookingsForUserUnauthorized with default headers values
func NewGetBookingsForUserUnauthorized() *GetBookingsForUserUnauthorized {
	return &GetBookingsForUserUnauthorized{}
}

/*
GetBookingsForUserUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetBookingsForUserUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this get bookings for user unauthorized response has a 2xx status code
func (o *GetBookingsForUserUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bookings for user unauthorized response has a 3xx status code
func (o *GetBookingsForUserUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bookings for user unauthorized response has a 4xx status code
func (o *GetBookingsForUserUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get bookings for user unauthorized response has a 5xx status code
func (o *GetBookingsForUserUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get bookings for user unauthorized response a status code equal to that given
func (o *GetBookingsForUserUnauthorized) IsCode(code int) bool {
	return code == 401
}

func (o *GetBookingsForUserUnauthorized) Error() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserUnauthorized  %+v", 401, o.Payload)
}

func (o *GetBookingsForUserUnauthorized) String() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserUnauthorized  %+v", 401, o.Payload)
}

func (o *GetBookingsForUserUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBookingsForUserUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBookingsForUserNotFound creates a GetBookingsForUserNotFound with default headers values
func NewGetBookingsForUserNotFound() *GetBookingsForUserNotFound {
	return &GetBookingsForUserNotFound{}
}

/*
GetBookingsForUserNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type GetBookingsForUserNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this get bookings for user not found response has a 2xx status code
func (o *GetBookingsForUserNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bookings for user not found response has a 3xx status code
func (o *GetBookingsForUserNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bookings for user not found response has a 4xx status code
func (o *GetBookingsForUserNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get bookings for user not found response has a 5xx status code
func (o *GetBookingsForUserNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get bookings for user not found response a status code equal to that given
func (o *GetBookingsForUserNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *GetBookingsForUserNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserNotFound  %+v", 404, o.Payload)
}

func (o *GetBookingsForUserNotFound) String() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserNotFound  %+v", 404, o.Payload)
}

func (o *GetBookingsForUserNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBookingsForUserNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetBookingsForUserInternalServerError creates a GetBookingsForUserInternalServerError with default headers values
func NewGetBookingsForUserInternalServerError() *GetBookingsForUserInternalServerError {
	return &GetBookingsForUserInternalServerError{}
}

/*
GetBookingsForUserInternalServerError describes a response with status code 500, with default header values.

Internal Error
*/
type GetBookingsForUserInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get bookings for user internal server error response has a 2xx status code
func (o *GetBookingsForUserInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get bookings for user internal server error response has a 3xx status code
func (o *GetBookingsForUserInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get bookings for user internal server error response has a 4xx status code
func (o *GetBookingsForUserInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get bookings for user internal server error response has a 5xx status code
func (o *GetBookingsForUserInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get bookings for user internal server error response a status code equal to that given
func (o *GetBookingsForUserInternalServerError) IsCode(code int) bool {
	return code == 500
}

func (o *GetBookingsForUserInternalServerError) Error() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserInternalServerError  %+v", 500, o.Payload)
}

func (o *GetBookingsForUserInternalServerError) String() string {
	return fmt.Sprintf("[GET /users/{user_name}/bookings][%d] getBookingsForUserInternalServerError  %+v", 500, o.Payload)
}

func (o *GetBookingsForUserInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetBookingsForUserInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
