// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/practable/book/internal/client/models"
)

// NewQueryCalendarAvailabilityParams creates a new QueryCalendarAvailabilityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryCalendarAvailabilityParams() *QueryCalendarAvailabilityParams {
	return &QueryCalendarAvailabilityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryCalendarAvailabilityParamsWithTimeout creates a new QueryCalendarAvailabilityParams object
// with the ability to set a timeout on a request.
func NewQueryCalendarAvailabilityParamsWithTimeout(timeout time.Duration) *QueryCalendarAvailabilityParams {
	return &QueryCalendarAvailabilityParams{
		timeout: timeout,
	}
}

// NewQueryCalendarAvailabilityParamsWithContext creates a new QueryCalendarAvailabilityParams object
// with the ability to set a context for a request.
func NewQueryCalendarAvailabilityParamsWithContext(ctx context.Context) *QueryCalendarAvailabilityParams {
	return &QueryCalendarAvailabilityParams{
		Context: ctx,
	}
}

// NewQueryCalendarAvailabilityParamsWithHTTPClient creates a new QueryCalendarAvailabilityParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryCalendarAvailabilityParamsWithHTTPClient(client *http.Client) *QueryCalendarAvailabilityParams {
	return &QueryCalendarAvailabilityParams{
		HTTPClient: client,
	}
}

/*
QueryCalendarAvailabilityParams contains all the parameters to send to the API endpoint

	for the query calendar availability operation.

	Typically these are written to a http.Request.
*/
type QueryCalendarAvailabilityParams struct {

	// Request.
	Request *models.CalendarAvailabilityRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query calendar availability params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryCalendarAvailabilityParams) WithDefaults() *QueryCalendarAvailabilityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query calendar availability params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryCalendarAvailabilityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) WithTimeout(timeout time.Duration) *QueryCalendarAvailabilityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) WithContext(ctx context.Context) *QueryCalendarAvailabilityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) WithHTTPClient(client *http.Client) *QueryCalendarAvailabilityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) WithRequest(request *models.CalendarAvailabilityRequest) *QueryCalendarAvailabilityParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the query calendar availability params
func (o *QueryCalendarAvailabilityParams) SetRequest(request *models.CalendarAvailabilityRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *QueryCalendarAvailabilityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
