// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/practable/book/internal/serve/models"
)

// NewBeginBookingActivationParams creates a new BeginBookingActivationParams object
//
// There are no default values defined in the spec.
func NewBeginBookingActivationParams() BeginBookingActivationParams {

	return BeginBookingActivationParams{}
}

// BeginBookingActivationParams contains all the bound params for the begin booking activation operation
// typically these are obtained from a http.Request
//
// swagger:parameters BeginBookingActivation
type BeginBookingActivationParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  Max Length: 200
	  Min Length: 1
	  In: header
	*/
	IdempotencyKey string
	/*
	  Required: true
	  In: path
	*/
	BookingName string
	/*
	  Required: true
	  In: body
	*/
	Request *models.BookingActivationRequest
	/*
	  Required: true
	  In: path
	*/
	UserName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewBeginBookingActivationParams() beforehand.
func (o *BeginBookingActivationParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if err := o.bindIdempotencyKey(r.Header[http.CanonicalHeaderKey("Idempotency-Key")], true, route.Formats); err != nil {
		res = append(res, err)
	}

	rBookingName, rhkBookingName, _ := route.Params.GetOK("booking_name")
	if err := o.bindBookingName(rBookingName, rhkBookingName, route.Formats); err != nil {
		res = append(res, err)
	}

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.BookingActivationRequest
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("request", "body", ""))
			} else {
				res = append(res, errors.NewParseError("request", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Request = &body
			}
		}
	} else {
		res = append(res, errors.Required("request", "body", ""))
	}

	rUserName, rhkUserName, _ := route.Params.GetOK("user_name")
	if err := o.bindUserName(rUserName, rhkUserName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindIdempotencyKey binds and validates parameter IdempotencyKey from header.
func (o *BeginBookingActivationParams) bindIdempotencyKey(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("Idempotency-Key", "header", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true

	if err := validate.RequiredString("Idempotency-Key", "header", raw); err != nil {
		return err
	}
	o.IdempotencyKey = raw

	if err := o.validateIdempotencyKey(formats); err != nil {
		return err
	}

	return nil
}

// validateIdempotencyKey carries on validations for parameter IdempotencyKey
func (o *BeginBookingActivationParams) validateIdempotencyKey(formats strfmt.Registry) error {

	if err := validate.MinLength("Idempotency-Key", "header", o.IdempotencyKey, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("Idempotency-Key", "header", o.IdempotencyKey, 200); err != nil {
		return err
	}

	return nil
}

// bindBookingName binds and validates parameter BookingName from path.
func (o *BeginBookingActivationParams) bindBookingName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.BookingName = raw

	return nil
}

// bindUserName binds and validates parameter UserName from path.
func (o *BeginBookingActivationParams) bindUserName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UserName = raw

	return nil
}
