// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"

	"github.com/timdrysdale/interval/internal/serve/models"
)

// NewCancelBookingParams creates a new CancelBookingParams object
//
// There are no default values defined in the spec.
func NewCancelBookingParams() CancelBookingParams {

	return CancelBookingParams{}
}

// CancelBookingParams contains all the bound params for the cancel booking operation
// typically these are obtained from a http.Request
//
// swagger:parameters CancelBooking
type CancelBookingParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	Booking *models.Booking
	/*
	  Required: true
	  In: path
	*/
	BookingName string
	/*
	  Required: true
	  In: path
	*/
	UserName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCancelBookingParams() beforehand.
func (o *CancelBookingParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Booking
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("booking", "body", ""))
			} else {
				res = append(res, errors.NewParseError("booking", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Booking = &body
			}
		}
	} else {
		res = append(res, errors.Required("booking", "body", ""))
	}

	rBookingName, rhkBookingName, _ := route.Params.GetOK("booking_name")
	if err := o.bindBookingName(rBookingName, rhkBookingName, route.Formats); err != nil {
		res = append(res, err)
	}

	rUserName, rhkUserName, _ := route.Params.GetOK("user_name")
	if err := o.bindUserName(rUserName, rhkUserName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindBookingName binds and validates parameter BookingName from path.
func (o *CancelBookingParams) bindBookingName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.BookingName = raw

	return nil
}

// bindUserName binds and validates parameter UserName from path.
func (o *CancelBookingParams) bindUserName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.UserName = raw

	return nil
}
