// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGroupsForUserHandlerFunc turns a function with the right signature into a get groups for user handler
type GetGroupsForUserHandlerFunc func(GetGroupsForUserParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGroupsForUserHandlerFunc) Handle(params GetGroupsForUserParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetGroupsForUserHandler interface for that can handle valid get groups for user params
type GetGroupsForUserHandler interface {
	Handle(GetGroupsForUserParams, interface{}) middleware.Responder
}

// NewGetGroupsForUser creates a new http.Handler for the get groups for user operation
func NewGetGroupsForUser(ctx *middleware.Context, handler GetGroupsForUserHandler) *GetGroupsForUser {
	return &GetGroupsForUser{Context: ctx, Handler: handler}
}

/* GetGroupsForUser swagger:route GET /users/{user_name}/groups users getGroupsForUser

Get all current groups for user

Get all current groups for user. This only returns groups that are currently listed within the user's groups. Group data includes a description, but not policies.

*/
type GetGroupsForUser struct {
	Context *middleware.Context
	Handler GetGroupsForUserHandler
}

func (o *GetGroupsForUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGroupsForUserParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
