// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// MakeCalendarBookingOKCode is the HTTP code returned for type MakeCalendarBookingOK
const MakeCalendarBookingOKCode int = 200

/*
MakeCalendarBookingOK Created or exact retry

swagger:response makeCalendarBookingOK
*/
type MakeCalendarBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.Booking `json:"body,omitempty"`
}

// NewMakeCalendarBookingOK creates MakeCalendarBookingOK with default headers values
func NewMakeCalendarBookingOK() *MakeCalendarBookingOK {

	return &MakeCalendarBookingOK{}
}

// WithPayload adds the payload to the make calendar booking o k response
func (o *MakeCalendarBookingOK) WithPayload(payload *models.Booking) *MakeCalendarBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make calendar booking o k response
func (o *MakeCalendarBookingOK) SetPayload(payload *models.Booking) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeCalendarBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeCalendarBookingBadRequestCode is the HTTP code returned for type MakeCalendarBookingBadRequest
const MakeCalendarBookingBadRequestCode int = 400

/*
MakeCalendarBookingBadRequest The request is malformed or exceeds calendar query limits

swagger:response makeCalendarBookingBadRequest
*/
type MakeCalendarBookingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeCalendarBookingBadRequest creates MakeCalendarBookingBadRequest with default headers values
func NewMakeCalendarBookingBadRequest() *MakeCalendarBookingBadRequest {

	return &MakeCalendarBookingBadRequest{}
}

// WithPayload adds the payload to the make calendar booking bad request response
func (o *MakeCalendarBookingBadRequest) WithPayload(payload *models.Error) *MakeCalendarBookingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make calendar booking bad request response
func (o *MakeCalendarBookingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeCalendarBookingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeCalendarBookingUnauthorizedCode is the HTTP code returned for type MakeCalendarBookingUnauthorized
const MakeCalendarBookingUnauthorizedCode int = 401

/*
MakeCalendarBookingUnauthorized Unauthorized

swagger:response makeCalendarBookingUnauthorized
*/
type MakeCalendarBookingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeCalendarBookingUnauthorized creates MakeCalendarBookingUnauthorized with default headers values
func NewMakeCalendarBookingUnauthorized() *MakeCalendarBookingUnauthorized {

	return &MakeCalendarBookingUnauthorized{}
}

// WithPayload adds the payload to the make calendar booking unauthorized response
func (o *MakeCalendarBookingUnauthorized) WithPayload(payload *models.Error) *MakeCalendarBookingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make calendar booking unauthorized response
func (o *MakeCalendarBookingUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeCalendarBookingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeCalendarBookingNotFoundCode is the HTTP code returned for type MakeCalendarBookingNotFound
const MakeCalendarBookingNotFoundCode int = 404

/*
MakeCalendarBookingNotFound The specified resource was not found

swagger:response makeCalendarBookingNotFound
*/
type MakeCalendarBookingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeCalendarBookingNotFound creates MakeCalendarBookingNotFound with default headers values
func NewMakeCalendarBookingNotFound() *MakeCalendarBookingNotFound {

	return &MakeCalendarBookingNotFound{}
}

// WithPayload adds the payload to the make calendar booking not found response
func (o *MakeCalendarBookingNotFound) WithPayload(payload *models.Error) *MakeCalendarBookingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make calendar booking not found response
func (o *MakeCalendarBookingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeCalendarBookingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeCalendarBookingConflictCode is the HTTP code returned for type MakeCalendarBookingConflict
const MakeCalendarBookingConflictCode int = 409

/*
MakeCalendarBookingConflict The booking was changed, started, or conflicts with the proposed replacement

swagger:response makeCalendarBookingConflict
*/
type MakeCalendarBookingConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeCalendarBookingConflict creates MakeCalendarBookingConflict with default headers values
func NewMakeCalendarBookingConflict() *MakeCalendarBookingConflict {

	return &MakeCalendarBookingConflict{}
}

// WithPayload adds the payload to the make calendar booking conflict response
func (o *MakeCalendarBookingConflict) WithPayload(payload *models.Error) *MakeCalendarBookingConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make calendar booking conflict response
func (o *MakeCalendarBookingConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeCalendarBookingConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// MakeCalendarBookingInternalServerErrorCode is the HTTP code returned for type MakeCalendarBookingInternalServerError
const MakeCalendarBookingInternalServerErrorCode int = 500

/*
MakeCalendarBookingInternalServerError Internal Error

swagger:response makeCalendarBookingInternalServerError
*/
type MakeCalendarBookingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewMakeCalendarBookingInternalServerError creates MakeCalendarBookingInternalServerError with default headers values
func NewMakeCalendarBookingInternalServerError() *MakeCalendarBookingInternalServerError {

	return &MakeCalendarBookingInternalServerError{}
}

// WithPayload adds the payload to the make calendar booking internal server error response
func (o *MakeCalendarBookingInternalServerError) WithPayload(payload *models.Error) *MakeCalendarBookingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the make calendar booking internal server error response
func (o *MakeCalendarBookingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *MakeCalendarBookingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
