// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// QueryCalendarAvailabilityHandlerFunc turns a function with the right signature into a query calendar availability handler
type QueryCalendarAvailabilityHandlerFunc func(QueryCalendarAvailabilityParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn QueryCalendarAvailabilityHandlerFunc) Handle(params QueryCalendarAvailabilityParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// QueryCalendarAvailabilityHandler interface for that can handle valid query calendar availability params
type QueryCalendarAvailabilityHandler interface {
	Handle(QueryCalendarAvailabilityParams, interface{}) middleware.Responder
}

// NewQueryCalendarAvailability creates a new http.Handler for the query calendar availability operation
func NewQueryCalendarAvailability(ctx *middleware.Context, handler QueryCalendarAvailabilityHandler) *QueryCalendarAvailability {
	return &QueryCalendarAvailability{Context: ctx, Handler: handler}
}

/*
	QueryCalendarAvailability swagger:route POST /calendar/availability users queryCalendarAvailability

# Query aggregate availability for a calendar range

Returns sampled availability counts for a policy pool optionally narrowed by resource or structured properties. It never reveals other users.
*/
type QueryCalendarAvailability struct {
	Context *middleware.Context
	Handler QueryCalendarAvailabilityHandler
}

func (o *QueryCalendarAvailability) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewQueryCalendarAvailabilityParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
