// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/practable/book/internal/serve/models"
)

// RescheduleCalendarBookingOKCode is the HTTP code returned for type RescheduleCalendarBookingOK
const RescheduleCalendarBookingOKCode int = 200

/*
RescheduleCalendarBookingOK OK

swagger:response rescheduleCalendarBookingOK
*/
type RescheduleCalendarBookingOK struct {

	/*
	  In: Body
	*/
	Payload *models.BookingEdit `json:"body,omitempty"`
}

// NewRescheduleCalendarBookingOK creates RescheduleCalendarBookingOK with default headers values
func NewRescheduleCalendarBookingOK() *RescheduleCalendarBookingOK {

	return &RescheduleCalendarBookingOK{}
}

// WithPayload adds the payload to the reschedule calendar booking o k response
func (o *RescheduleCalendarBookingOK) WithPayload(payload *models.BookingEdit) *RescheduleCalendarBookingOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reschedule calendar booking o k response
func (o *RescheduleCalendarBookingOK) SetPayload(payload *models.BookingEdit) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescheduleCalendarBookingOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RescheduleCalendarBookingBadRequestCode is the HTTP code returned for type RescheduleCalendarBookingBadRequest
const RescheduleCalendarBookingBadRequestCode int = 400

/*
RescheduleCalendarBookingBadRequest The request is malformed or exceeds calendar query limits

swagger:response rescheduleCalendarBookingBadRequest
*/
type RescheduleCalendarBookingBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRescheduleCalendarBookingBadRequest creates RescheduleCalendarBookingBadRequest with default headers values
func NewRescheduleCalendarBookingBadRequest() *RescheduleCalendarBookingBadRequest {

	return &RescheduleCalendarBookingBadRequest{}
}

// WithPayload adds the payload to the reschedule calendar booking bad request response
func (o *RescheduleCalendarBookingBadRequest) WithPayload(payload *models.Error) *RescheduleCalendarBookingBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reschedule calendar booking bad request response
func (o *RescheduleCalendarBookingBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescheduleCalendarBookingBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RescheduleCalendarBookingUnauthorizedCode is the HTTP code returned for type RescheduleCalendarBookingUnauthorized
const RescheduleCalendarBookingUnauthorizedCode int = 401

/*
RescheduleCalendarBookingUnauthorized Unauthorized

swagger:response rescheduleCalendarBookingUnauthorized
*/
type RescheduleCalendarBookingUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRescheduleCalendarBookingUnauthorized creates RescheduleCalendarBookingUnauthorized with default headers values
func NewRescheduleCalendarBookingUnauthorized() *RescheduleCalendarBookingUnauthorized {

	return &RescheduleCalendarBookingUnauthorized{}
}

// WithPayload adds the payload to the reschedule calendar booking unauthorized response
func (o *RescheduleCalendarBookingUnauthorized) WithPayload(payload *models.Error) *RescheduleCalendarBookingUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reschedule calendar booking unauthorized response
func (o *RescheduleCalendarBookingUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescheduleCalendarBookingUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RescheduleCalendarBookingNotFoundCode is the HTTP code returned for type RescheduleCalendarBookingNotFound
const RescheduleCalendarBookingNotFoundCode int = 404

/*
RescheduleCalendarBookingNotFound The specified resource was not found

swagger:response rescheduleCalendarBookingNotFound
*/
type RescheduleCalendarBookingNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRescheduleCalendarBookingNotFound creates RescheduleCalendarBookingNotFound with default headers values
func NewRescheduleCalendarBookingNotFound() *RescheduleCalendarBookingNotFound {

	return &RescheduleCalendarBookingNotFound{}
}

// WithPayload adds the payload to the reschedule calendar booking not found response
func (o *RescheduleCalendarBookingNotFound) WithPayload(payload *models.Error) *RescheduleCalendarBookingNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reschedule calendar booking not found response
func (o *RescheduleCalendarBookingNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescheduleCalendarBookingNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RescheduleCalendarBookingConflictCode is the HTTP code returned for type RescheduleCalendarBookingConflict
const RescheduleCalendarBookingConflictCode int = 409

/*
RescheduleCalendarBookingConflict The booking was changed, started, or conflicts with the proposed replacement

swagger:response rescheduleCalendarBookingConflict
*/
type RescheduleCalendarBookingConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRescheduleCalendarBookingConflict creates RescheduleCalendarBookingConflict with default headers values
func NewRescheduleCalendarBookingConflict() *RescheduleCalendarBookingConflict {

	return &RescheduleCalendarBookingConflict{}
}

// WithPayload adds the payload to the reschedule calendar booking conflict response
func (o *RescheduleCalendarBookingConflict) WithPayload(payload *models.Error) *RescheduleCalendarBookingConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reschedule calendar booking conflict response
func (o *RescheduleCalendarBookingConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescheduleCalendarBookingConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RescheduleCalendarBookingInternalServerErrorCode is the HTTP code returned for type RescheduleCalendarBookingInternalServerError
const RescheduleCalendarBookingInternalServerErrorCode int = 500

/*
RescheduleCalendarBookingInternalServerError Internal Error

swagger:response rescheduleCalendarBookingInternalServerError
*/
type RescheduleCalendarBookingInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRescheduleCalendarBookingInternalServerError creates RescheduleCalendarBookingInternalServerError with default headers values
func NewRescheduleCalendarBookingInternalServerError() *RescheduleCalendarBookingInternalServerError {

	return &RescheduleCalendarBookingInternalServerError{}
}

// WithPayload adds the payload to the reschedule calendar booking internal server error response
func (o *RescheduleCalendarBookingInternalServerError) WithPayload(payload *models.Error) *RescheduleCalendarBookingInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the reschedule calendar booking internal server error response
func (o *RescheduleCalendarBookingInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RescheduleCalendarBookingInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
