// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewAcknowledgeOperationalAlertParams creates a new AcknowledgeOperationalAlertParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAcknowledgeOperationalAlertParams() *AcknowledgeOperationalAlertParams {
	return &AcknowledgeOperationalAlertParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAcknowledgeOperationalAlertParamsWithTimeout creates a new AcknowledgeOperationalAlertParams object
// with the ability to set a timeout on a request.
func NewAcknowledgeOperationalAlertParamsWithTimeout(timeout time.Duration) *AcknowledgeOperationalAlertParams {
	return &AcknowledgeOperationalAlertParams{
		timeout: timeout,
	}
}

// NewAcknowledgeOperationalAlertParamsWithContext creates a new AcknowledgeOperationalAlertParams object
// with the ability to set a context for a request.
func NewAcknowledgeOperationalAlertParamsWithContext(ctx context.Context) *AcknowledgeOperationalAlertParams {
	return &AcknowledgeOperationalAlertParams{
		Context: ctx,
	}
}

// NewAcknowledgeOperationalAlertParamsWithHTTPClient creates a new AcknowledgeOperationalAlertParams object
// with the ability to set a custom HTTPClient for a request.
func NewAcknowledgeOperationalAlertParamsWithHTTPClient(client *http.Client) *AcknowledgeOperationalAlertParams {
	return &AcknowledgeOperationalAlertParams{
		HTTPClient: client,
	}
}

/*
AcknowledgeOperationalAlertParams contains all the parameters to send to the API endpoint

	for the acknowledge operational alert operation.

	Typically these are written to a http.Request.
*/
type AcknowledgeOperationalAlertParams struct {

	// AlertID.
	//
	// Format: int64
	AlertID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the acknowledge operational alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcknowledgeOperationalAlertParams) WithDefaults() *AcknowledgeOperationalAlertParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the acknowledge operational alert params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AcknowledgeOperationalAlertParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) WithTimeout(timeout time.Duration) *AcknowledgeOperationalAlertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) WithContext(ctx context.Context) *AcknowledgeOperationalAlertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) WithHTTPClient(client *http.Client) *AcknowledgeOperationalAlertParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAlertID adds the alertID to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) WithAlertID(alertID int64) *AcknowledgeOperationalAlertParams {
	o.SetAlertID(alertID)
	return o
}

// SetAlertID adds the alertId to the acknowledge operational alert params
func (o *AcknowledgeOperationalAlertParams) SetAlertID(alertID int64) {
	o.AlertID = alertID
}

// WriteToRequest writes these params to a swagger request
func (o *AcknowledgeOperationalAlertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param alert_id
	if err := r.SetPathParam("alert_id", swag.FormatInt64(o.AlertID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
