// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExportManifestParams creates a new ExportManifestParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExportManifestParams() *ExportManifestParams {
	return &ExportManifestParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExportManifestParamsWithTimeout creates a new ExportManifestParams object
// with the ability to set a timeout on a request.
func NewExportManifestParamsWithTimeout(timeout time.Duration) *ExportManifestParams {
	return &ExportManifestParams{
		timeout: timeout,
	}
}

// NewExportManifestParamsWithContext creates a new ExportManifestParams object
// with the ability to set a context for a request.
func NewExportManifestParamsWithContext(ctx context.Context) *ExportManifestParams {
	return &ExportManifestParams{
		Context: ctx,
	}
}

// NewExportManifestParamsWithHTTPClient creates a new ExportManifestParams object
// with the ability to set a custom HTTPClient for a request.
func NewExportManifestParamsWithHTTPClient(client *http.Client) *ExportManifestParams {
	return &ExportManifestParams{
		HTTPClient: client,
	}
}

/* ExportManifestParams contains all the parameters to send to the API endpoint
   for the export manifest operation.

   Typically these are written to a http.Request.
*/
type ExportManifestParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the export manifest params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportManifestParams) WithDefaults() *ExportManifestParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the export manifest params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExportManifestParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the export manifest params
func (o *ExportManifestParams) WithTimeout(timeout time.Duration) *ExportManifestParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the export manifest params
func (o *ExportManifestParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the export manifest params
func (o *ExportManifestParams) WithContext(ctx context.Context) *ExportManifestParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the export manifest params
func (o *ExportManifestParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the export manifest params
func (o *ExportManifestParams) WithHTTPClient(client *http.Client) *ExportManifestParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the export manifest params
func (o *ExportManifestParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ExportManifestParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
