// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetResourceIsAvailableParams creates a new GetResourceIsAvailableParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetResourceIsAvailableParams() *GetResourceIsAvailableParams {
	return &GetResourceIsAvailableParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetResourceIsAvailableParamsWithTimeout creates a new GetResourceIsAvailableParams object
// with the ability to set a timeout on a request.
func NewGetResourceIsAvailableParamsWithTimeout(timeout time.Duration) *GetResourceIsAvailableParams {
	return &GetResourceIsAvailableParams{
		timeout: timeout,
	}
}

// NewGetResourceIsAvailableParamsWithContext creates a new GetResourceIsAvailableParams object
// with the ability to set a context for a request.
func NewGetResourceIsAvailableParamsWithContext(ctx context.Context) *GetResourceIsAvailableParams {
	return &GetResourceIsAvailableParams{
		Context: ctx,
	}
}

// NewGetResourceIsAvailableParamsWithHTTPClient creates a new GetResourceIsAvailableParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetResourceIsAvailableParamsWithHTTPClient(client *http.Client) *GetResourceIsAvailableParams {
	return &GetResourceIsAvailableParams{
		HTTPClient: client,
	}
}

/*
GetResourceIsAvailableParams contains all the parameters to send to the API endpoint

	for the get resource is available operation.

	Typically these are written to a http.Request.
*/
type GetResourceIsAvailableParams struct {

	// ResourceName.
	ResourceName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get resource is available params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourceIsAvailableParams) WithDefaults() *GetResourceIsAvailableParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get resource is available params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetResourceIsAvailableParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get resource is available params
func (o *GetResourceIsAvailableParams) WithTimeout(timeout time.Duration) *GetResourceIsAvailableParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get resource is available params
func (o *GetResourceIsAvailableParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get resource is available params
func (o *GetResourceIsAvailableParams) WithContext(ctx context.Context) *GetResourceIsAvailableParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get resource is available params
func (o *GetResourceIsAvailableParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get resource is available params
func (o *GetResourceIsAvailableParams) WithHTTPClient(client *http.Client) *GetResourceIsAvailableParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get resource is available params
func (o *GetResourceIsAvailableParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceName adds the resourceName to the get resource is available params
func (o *GetResourceIsAvailableParams) WithResourceName(resourceName string) *GetResourceIsAvailableParams {
	o.SetResourceName(resourceName)
	return o
}

// SetResourceName adds the resourceName to the get resource is available params
func (o *GetResourceIsAvailableParams) SetResourceName(resourceName string) {
	o.ResourceName = resourceName
}

// WriteToRequest writes these params to a swagger request
func (o *GetResourceIsAvailableParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param resource_name
	if err := r.SetPathParam("resource_name", o.ResourceName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
