// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/practable/book/internal/client/models"
)

// ListResourceReleasesReader is a Reader for the ListResourceReleases structure.
type ListResourceReleasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListResourceReleasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListResourceReleasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewListResourceReleasesUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewListResourceReleasesInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /admin/resource-releases] ListResourceReleases", response, response.Code())
	}
}

// NewListResourceReleasesOK creates a ListResourceReleasesOK with default headers values
func NewListResourceReleasesOK() *ListResourceReleasesOK {
	return &ListResourceReleasesOK{}
}

/*
ListResourceReleasesOK describes a response with status code 200, with default header values.

OK
*/
type ListResourceReleasesOK struct {
	Payload []*models.ResourceReleaseState
}

// IsSuccess returns true when this list resource releases o k response has a 2xx status code
func (o *ListResourceReleasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list resource releases o k response has a 3xx status code
func (o *ListResourceReleasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list resource releases o k response has a 4xx status code
func (o *ListResourceReleasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list resource releases o k response has a 5xx status code
func (o *ListResourceReleasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list resource releases o k response a status code equal to that given
func (o *ListResourceReleasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the list resource releases o k response
func (o *ListResourceReleasesOK) Code() int {
	return 200
}

func (o *ListResourceReleasesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/resource-releases][%d] listResourceReleasesOK %s", 200, payload)
}

func (o *ListResourceReleasesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/resource-releases][%d] listResourceReleasesOK %s", 200, payload)
}

func (o *ListResourceReleasesOK) GetPayload() []*models.ResourceReleaseState {
	return o.Payload
}

func (o *ListResourceReleasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourceReleasesUnauthorized creates a ListResourceReleasesUnauthorized with default headers values
func NewListResourceReleasesUnauthorized() *ListResourceReleasesUnauthorized {
	return &ListResourceReleasesUnauthorized{}
}

/*
ListResourceReleasesUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type ListResourceReleasesUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this list resource releases unauthorized response has a 2xx status code
func (o *ListResourceReleasesUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list resource releases unauthorized response has a 3xx status code
func (o *ListResourceReleasesUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list resource releases unauthorized response has a 4xx status code
func (o *ListResourceReleasesUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this list resource releases unauthorized response has a 5xx status code
func (o *ListResourceReleasesUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this list resource releases unauthorized response a status code equal to that given
func (o *ListResourceReleasesUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the list resource releases unauthorized response
func (o *ListResourceReleasesUnauthorized) Code() int {
	return 401
}

func (o *ListResourceReleasesUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/resource-releases][%d] listResourceReleasesUnauthorized %s", 401, payload)
}

func (o *ListResourceReleasesUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/resource-releases][%d] listResourceReleasesUnauthorized %s", 401, payload)
}

func (o *ListResourceReleasesUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListResourceReleasesUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListResourceReleasesInternalServerError creates a ListResourceReleasesInternalServerError with default headers values
func NewListResourceReleasesInternalServerError() *ListResourceReleasesInternalServerError {
	return &ListResourceReleasesInternalServerError{}
}

/*
ListResourceReleasesInternalServerError describes a response with status code 500, with default header values.

Internal Error
*/
type ListResourceReleasesInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this list resource releases internal server error response has a 2xx status code
func (o *ListResourceReleasesInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list resource releases internal server error response has a 3xx status code
func (o *ListResourceReleasesInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list resource releases internal server error response has a 4xx status code
func (o *ListResourceReleasesInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this list resource releases internal server error response has a 5xx status code
func (o *ListResourceReleasesInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this list resource releases internal server error response a status code equal to that given
func (o *ListResourceReleasesInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the list resource releases internal server error response
func (o *ListResourceReleasesInternalServerError) Code() int {
	return 500
}

func (o *ListResourceReleasesInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/resource-releases][%d] listResourceReleasesInternalServerError %s", 500, payload)
}

func (o *ListResourceReleasesInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/resource-releases][%d] listResourceReleasesInternalServerError %s", 500, payload)
}

func (o *ListResourceReleasesInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *ListResourceReleasesInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
