// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/practable/book/internal/client/models"
)

// MakeMaintenanceBookingReader is a Reader for the MakeMaintenanceBooking structure.
type MakeMaintenanceBookingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *MakeMaintenanceBookingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewMakeMaintenanceBookingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewMakeMaintenanceBookingUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewMakeMaintenanceBookingNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewMakeMaintenanceBookingConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewMakeMaintenanceBookingInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[POST /admin/maintenance/bookings] MakeMaintenanceBooking", response, response.Code())
	}
}

// NewMakeMaintenanceBookingOK creates a MakeMaintenanceBookingOK with default headers values
func NewMakeMaintenanceBookingOK() *MakeMaintenanceBookingOK {
	return &MakeMaintenanceBookingOK{}
}

/*
MakeMaintenanceBookingOK describes a response with status code 200, with default header values.

OK
*/
type MakeMaintenanceBookingOK struct {
	Payload *models.Booking
}

// IsSuccess returns true when this make maintenance booking o k response has a 2xx status code
func (o *MakeMaintenanceBookingOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this make maintenance booking o k response has a 3xx status code
func (o *MakeMaintenanceBookingOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this make maintenance booking o k response has a 4xx status code
func (o *MakeMaintenanceBookingOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this make maintenance booking o k response has a 5xx status code
func (o *MakeMaintenanceBookingOK) IsServerError() bool {
	return false
}

// IsCode returns true when this make maintenance booking o k response a status code equal to that given
func (o *MakeMaintenanceBookingOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the make maintenance booking o k response
func (o *MakeMaintenanceBookingOK) Code() int {
	return 200
}

func (o *MakeMaintenanceBookingOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingOK %s", 200, payload)
}

func (o *MakeMaintenanceBookingOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingOK %s", 200, payload)
}

func (o *MakeMaintenanceBookingOK) GetPayload() *models.Booking {
	return o.Payload
}

func (o *MakeMaintenanceBookingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Booking)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMakeMaintenanceBookingUnauthorized creates a MakeMaintenanceBookingUnauthorized with default headers values
func NewMakeMaintenanceBookingUnauthorized() *MakeMaintenanceBookingUnauthorized {
	return &MakeMaintenanceBookingUnauthorized{}
}

/*
MakeMaintenanceBookingUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type MakeMaintenanceBookingUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this make maintenance booking unauthorized response has a 2xx status code
func (o *MakeMaintenanceBookingUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this make maintenance booking unauthorized response has a 3xx status code
func (o *MakeMaintenanceBookingUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this make maintenance booking unauthorized response has a 4xx status code
func (o *MakeMaintenanceBookingUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this make maintenance booking unauthorized response has a 5xx status code
func (o *MakeMaintenanceBookingUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this make maintenance booking unauthorized response a status code equal to that given
func (o *MakeMaintenanceBookingUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the make maintenance booking unauthorized response
func (o *MakeMaintenanceBookingUnauthorized) Code() int {
	return 401
}

func (o *MakeMaintenanceBookingUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingUnauthorized %s", 401, payload)
}

func (o *MakeMaintenanceBookingUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingUnauthorized %s", 401, payload)
}

func (o *MakeMaintenanceBookingUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *MakeMaintenanceBookingUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMakeMaintenanceBookingNotFound creates a MakeMaintenanceBookingNotFound with default headers values
func NewMakeMaintenanceBookingNotFound() *MakeMaintenanceBookingNotFound {
	return &MakeMaintenanceBookingNotFound{}
}

/*
MakeMaintenanceBookingNotFound describes a response with status code 404, with default header values.

The specified resource was not found
*/
type MakeMaintenanceBookingNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this make maintenance booking not found response has a 2xx status code
func (o *MakeMaintenanceBookingNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this make maintenance booking not found response has a 3xx status code
func (o *MakeMaintenanceBookingNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this make maintenance booking not found response has a 4xx status code
func (o *MakeMaintenanceBookingNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this make maintenance booking not found response has a 5xx status code
func (o *MakeMaintenanceBookingNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this make maintenance booking not found response a status code equal to that given
func (o *MakeMaintenanceBookingNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the make maintenance booking not found response
func (o *MakeMaintenanceBookingNotFound) Code() int {
	return 404
}

func (o *MakeMaintenanceBookingNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingNotFound %s", 404, payload)
}

func (o *MakeMaintenanceBookingNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingNotFound %s", 404, payload)
}

func (o *MakeMaintenanceBookingNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *MakeMaintenanceBookingNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMakeMaintenanceBookingConflict creates a MakeMaintenanceBookingConflict with default headers values
func NewMakeMaintenanceBookingConflict() *MakeMaintenanceBookingConflict {
	return &MakeMaintenanceBookingConflict{}
}

/*
MakeMaintenanceBookingConflict describes a response with status code 409, with default header values.

The booking was changed, started, or conflicts with the proposed replacement
*/
type MakeMaintenanceBookingConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this make maintenance booking conflict response has a 2xx status code
func (o *MakeMaintenanceBookingConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this make maintenance booking conflict response has a 3xx status code
func (o *MakeMaintenanceBookingConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this make maintenance booking conflict response has a 4xx status code
func (o *MakeMaintenanceBookingConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this make maintenance booking conflict response has a 5xx status code
func (o *MakeMaintenanceBookingConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this make maintenance booking conflict response a status code equal to that given
func (o *MakeMaintenanceBookingConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the make maintenance booking conflict response
func (o *MakeMaintenanceBookingConflict) Code() int {
	return 409
}

func (o *MakeMaintenanceBookingConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingConflict %s", 409, payload)
}

func (o *MakeMaintenanceBookingConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingConflict %s", 409, payload)
}

func (o *MakeMaintenanceBookingConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *MakeMaintenanceBookingConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewMakeMaintenanceBookingInternalServerError creates a MakeMaintenanceBookingInternalServerError with default headers values
func NewMakeMaintenanceBookingInternalServerError() *MakeMaintenanceBookingInternalServerError {
	return &MakeMaintenanceBookingInternalServerError{}
}

/*
MakeMaintenanceBookingInternalServerError describes a response with status code 500, with default header values.

Internal Error
*/
type MakeMaintenanceBookingInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this make maintenance booking internal server error response has a 2xx status code
func (o *MakeMaintenanceBookingInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this make maintenance booking internal server error response has a 3xx status code
func (o *MakeMaintenanceBookingInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this make maintenance booking internal server error response has a 4xx status code
func (o *MakeMaintenanceBookingInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this make maintenance booking internal server error response has a 5xx status code
func (o *MakeMaintenanceBookingInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this make maintenance booking internal server error response a status code equal to that given
func (o *MakeMaintenanceBookingInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the make maintenance booking internal server error response
func (o *MakeMaintenanceBookingInternalServerError) Code() int {
	return 500
}

func (o *MakeMaintenanceBookingInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingInternalServerError %s", 500, payload)
}

func (o *MakeMaintenanceBookingInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /admin/maintenance/bookings][%d] makeMaintenanceBookingInternalServerError %s", 500, payload)
}

func (o *MakeMaintenanceBookingInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *MakeMaintenanceBookingInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
