// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewMakeResourceMaintenanceBookingParams creates a new MakeResourceMaintenanceBookingParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewMakeResourceMaintenanceBookingParams() *MakeResourceMaintenanceBookingParams {
	return &MakeResourceMaintenanceBookingParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewMakeResourceMaintenanceBookingParamsWithTimeout creates a new MakeResourceMaintenanceBookingParams object
// with the ability to set a timeout on a request.
func NewMakeResourceMaintenanceBookingParamsWithTimeout(timeout time.Duration) *MakeResourceMaintenanceBookingParams {
	return &MakeResourceMaintenanceBookingParams{
		timeout: timeout,
	}
}

// NewMakeResourceMaintenanceBookingParamsWithContext creates a new MakeResourceMaintenanceBookingParams object
// with the ability to set a context for a request.
func NewMakeResourceMaintenanceBookingParamsWithContext(ctx context.Context) *MakeResourceMaintenanceBookingParams {
	return &MakeResourceMaintenanceBookingParams{
		Context: ctx,
	}
}

// NewMakeResourceMaintenanceBookingParamsWithHTTPClient creates a new MakeResourceMaintenanceBookingParams object
// with the ability to set a custom HTTPClient for a request.
func NewMakeResourceMaintenanceBookingParamsWithHTTPClient(client *http.Client) *MakeResourceMaintenanceBookingParams {
	return &MakeResourceMaintenanceBookingParams{
		HTTPClient: client,
	}
}

/*
MakeResourceMaintenanceBookingParams contains all the parameters to send to the API endpoint

	for the make resource maintenance booking operation.

	Typically these are written to a http.Request.
*/
type MakeResourceMaintenanceBookingParams struct {

	// From.
	//
	// Format: date-time
	From strfmt.DateTime

	// ResourceName.
	ResourceName string

	// To.
	//
	// Format: date-time
	To strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the make resource maintenance booking params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MakeResourceMaintenanceBookingParams) WithDefaults() *MakeResourceMaintenanceBookingParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the make resource maintenance booking params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *MakeResourceMaintenanceBookingParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) WithTimeout(timeout time.Duration) *MakeResourceMaintenanceBookingParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) WithContext(ctx context.Context) *MakeResourceMaintenanceBookingParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) WithHTTPClient(client *http.Client) *MakeResourceMaintenanceBookingParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) WithFrom(from strfmt.DateTime) *MakeResourceMaintenanceBookingParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) SetFrom(from strfmt.DateTime) {
	o.From = from
}

// WithResourceName adds the resourceName to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) WithResourceName(resourceName string) *MakeResourceMaintenanceBookingParams {
	o.SetResourceName(resourceName)
	return o
}

// SetResourceName adds the resourceName to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) SetResourceName(resourceName string) {
	o.ResourceName = resourceName
}

// WithTo adds the to to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) WithTo(to strfmt.DateTime) *MakeResourceMaintenanceBookingParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the make resource maintenance booking params
func (o *MakeResourceMaintenanceBookingParams) SetTo(to strfmt.DateTime) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *MakeResourceMaintenanceBookingParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param from
	qrFrom := o.From
	qFrom := qrFrom.String()
	if qFrom != "" {

		if err := r.SetQueryParam("from", qFrom); err != nil {
			return err
		}
	}

	// path param resource_name
	if err := r.SetPathParam("resource_name", o.ResourceName); err != nil {
		return err
	}

	// query param to
	qrTo := o.To
	qTo := qrTo.String()
	if qTo != "" {

		if err := r.SetQueryParam("to", qTo); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
