// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/practable/book/internal/client/models"
)

// QueryBookingRecordsReader is a Reader for the QueryBookingRecords structure.
type QueryBookingRecordsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *QueryBookingRecordsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewQueryBookingRecordsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewQueryBookingRecordsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewQueryBookingRecordsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewQueryBookingRecordsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /admin/booking-records] QueryBookingRecords", response, response.Code())
	}
}

// NewQueryBookingRecordsOK creates a QueryBookingRecordsOK with default headers values
func NewQueryBookingRecordsOK() *QueryBookingRecordsOK {
	return &QueryBookingRecordsOK{}
}

/*
QueryBookingRecordsOK describes a response with status code 200, with default header values.

OK
*/
type QueryBookingRecordsOK struct {
	Payload []*models.AdminBookingRecord
}

// IsSuccess returns true when this query booking records o k response has a 2xx status code
func (o *QueryBookingRecordsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this query booking records o k response has a 3xx status code
func (o *QueryBookingRecordsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query booking records o k response has a 4xx status code
func (o *QueryBookingRecordsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this query booking records o k response has a 5xx status code
func (o *QueryBookingRecordsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this query booking records o k response a status code equal to that given
func (o *QueryBookingRecordsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the query booking records o k response
func (o *QueryBookingRecordsOK) Code() int {
	return 200
}

func (o *QueryBookingRecordsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsOK %s", 200, payload)
}

func (o *QueryBookingRecordsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsOK %s", 200, payload)
}

func (o *QueryBookingRecordsOK) GetPayload() []*models.AdminBookingRecord {
	return o.Payload
}

func (o *QueryBookingRecordsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryBookingRecordsBadRequest creates a QueryBookingRecordsBadRequest with default headers values
func NewQueryBookingRecordsBadRequest() *QueryBookingRecordsBadRequest {
	return &QueryBookingRecordsBadRequest{}
}

/*
QueryBookingRecordsBadRequest describes a response with status code 400, with default header values.

The request is malformed or exceeds calendar query limits
*/
type QueryBookingRecordsBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this query booking records bad request response has a 2xx status code
func (o *QueryBookingRecordsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query booking records bad request response has a 3xx status code
func (o *QueryBookingRecordsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query booking records bad request response has a 4xx status code
func (o *QueryBookingRecordsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this query booking records bad request response has a 5xx status code
func (o *QueryBookingRecordsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this query booking records bad request response a status code equal to that given
func (o *QueryBookingRecordsBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the query booking records bad request response
func (o *QueryBookingRecordsBadRequest) Code() int {
	return 400
}

func (o *QueryBookingRecordsBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsBadRequest %s", 400, payload)
}

func (o *QueryBookingRecordsBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsBadRequest %s", 400, payload)
}

func (o *QueryBookingRecordsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *QueryBookingRecordsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryBookingRecordsUnauthorized creates a QueryBookingRecordsUnauthorized with default headers values
func NewQueryBookingRecordsUnauthorized() *QueryBookingRecordsUnauthorized {
	return &QueryBookingRecordsUnauthorized{}
}

/*
QueryBookingRecordsUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type QueryBookingRecordsUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this query booking records unauthorized response has a 2xx status code
func (o *QueryBookingRecordsUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query booking records unauthorized response has a 3xx status code
func (o *QueryBookingRecordsUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query booking records unauthorized response has a 4xx status code
func (o *QueryBookingRecordsUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this query booking records unauthorized response has a 5xx status code
func (o *QueryBookingRecordsUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this query booking records unauthorized response a status code equal to that given
func (o *QueryBookingRecordsUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the query booking records unauthorized response
func (o *QueryBookingRecordsUnauthorized) Code() int {
	return 401
}

func (o *QueryBookingRecordsUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsUnauthorized %s", 401, payload)
}

func (o *QueryBookingRecordsUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsUnauthorized %s", 401, payload)
}

func (o *QueryBookingRecordsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *QueryBookingRecordsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewQueryBookingRecordsInternalServerError creates a QueryBookingRecordsInternalServerError with default headers values
func NewQueryBookingRecordsInternalServerError() *QueryBookingRecordsInternalServerError {
	return &QueryBookingRecordsInternalServerError{}
}

/*
QueryBookingRecordsInternalServerError describes a response with status code 500, with default header values.

Internal Error
*/
type QueryBookingRecordsInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this query booking records internal server error response has a 2xx status code
func (o *QueryBookingRecordsInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this query booking records internal server error response has a 3xx status code
func (o *QueryBookingRecordsInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this query booking records internal server error response has a 4xx status code
func (o *QueryBookingRecordsInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this query booking records internal server error response has a 5xx status code
func (o *QueryBookingRecordsInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this query booking records internal server error response a status code equal to that given
func (o *QueryBookingRecordsInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the query booking records internal server error response
func (o *QueryBookingRecordsInternalServerError) Code() int {
	return 500
}

func (o *QueryBookingRecordsInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsInternalServerError %s", 500, payload)
}

func (o *QueryBookingRecordsInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /admin/booking-records][%d] queryBookingRecordsInternalServerError %s", 500, payload)
}

func (o *QueryBookingRecordsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *QueryBookingRecordsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
