// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewQueryBookingRecordsParams creates a new QueryBookingRecordsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewQueryBookingRecordsParams() *QueryBookingRecordsParams {
	return &QueryBookingRecordsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewQueryBookingRecordsParamsWithTimeout creates a new QueryBookingRecordsParams object
// with the ability to set a timeout on a request.
func NewQueryBookingRecordsParamsWithTimeout(timeout time.Duration) *QueryBookingRecordsParams {
	return &QueryBookingRecordsParams{
		timeout: timeout,
	}
}

// NewQueryBookingRecordsParamsWithContext creates a new QueryBookingRecordsParams object
// with the ability to set a context for a request.
func NewQueryBookingRecordsParamsWithContext(ctx context.Context) *QueryBookingRecordsParams {
	return &QueryBookingRecordsParams{
		Context: ctx,
	}
}

// NewQueryBookingRecordsParamsWithHTTPClient creates a new QueryBookingRecordsParams object
// with the ability to set a custom HTTPClient for a request.
func NewQueryBookingRecordsParamsWithHTTPClient(client *http.Client) *QueryBookingRecordsParams {
	return &QueryBookingRecordsParams{
		HTTPClient: client,
	}
}

/*
QueryBookingRecordsParams contains all the parameters to send to the API endpoint

	for the query booking records operation.

	Typically these are written to a http.Request.
*/
type QueryBookingRecordsParams struct {

	// From.
	//
	// Format: date-time
	From *strfmt.DateTime

	// Limit.
	//
	// Format: int64
	// Default: 200
	Limit *int64

	// Policy.
	Policy *string

	// Resource.
	Resource *string

	// Slot.
	Slot *string

	// State.
	//
	// Default: "all"
	State *string

	// To.
	//
	// Format: date-time
	To *strfmt.DateTime

	// User.
	User *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the query booking records params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryBookingRecordsParams) WithDefaults() *QueryBookingRecordsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the query booking records params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *QueryBookingRecordsParams) SetDefaults() {
	var (
		limitDefault = int64(200)

		stateDefault = string("all")
	)

	val := QueryBookingRecordsParams{
		Limit: &limitDefault,
		State: &stateDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the query booking records params
func (o *QueryBookingRecordsParams) WithTimeout(timeout time.Duration) *QueryBookingRecordsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the query booking records params
func (o *QueryBookingRecordsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the query booking records params
func (o *QueryBookingRecordsParams) WithContext(ctx context.Context) *QueryBookingRecordsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the query booking records params
func (o *QueryBookingRecordsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the query booking records params
func (o *QueryBookingRecordsParams) WithHTTPClient(client *http.Client) *QueryBookingRecordsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the query booking records params
func (o *QueryBookingRecordsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFrom adds the from to the query booking records params
func (o *QueryBookingRecordsParams) WithFrom(from *strfmt.DateTime) *QueryBookingRecordsParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the query booking records params
func (o *QueryBookingRecordsParams) SetFrom(from *strfmt.DateTime) {
	o.From = from
}

// WithLimit adds the limit to the query booking records params
func (o *QueryBookingRecordsParams) WithLimit(limit *int64) *QueryBookingRecordsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the query booking records params
func (o *QueryBookingRecordsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPolicy adds the policy to the query booking records params
func (o *QueryBookingRecordsParams) WithPolicy(policy *string) *QueryBookingRecordsParams {
	o.SetPolicy(policy)
	return o
}

// SetPolicy adds the policy to the query booking records params
func (o *QueryBookingRecordsParams) SetPolicy(policy *string) {
	o.Policy = policy
}

// WithResource adds the resource to the query booking records params
func (o *QueryBookingRecordsParams) WithResource(resource *string) *QueryBookingRecordsParams {
	o.SetResource(resource)
	return o
}

// SetResource adds the resource to the query booking records params
func (o *QueryBookingRecordsParams) SetResource(resource *string) {
	o.Resource = resource
}

// WithSlot adds the slot to the query booking records params
func (o *QueryBookingRecordsParams) WithSlot(slot *string) *QueryBookingRecordsParams {
	o.SetSlot(slot)
	return o
}

// SetSlot adds the slot to the query booking records params
func (o *QueryBookingRecordsParams) SetSlot(slot *string) {
	o.Slot = slot
}

// WithState adds the state to the query booking records params
func (o *QueryBookingRecordsParams) WithState(state *string) *QueryBookingRecordsParams {
	o.SetState(state)
	return o
}

// SetState adds the state to the query booking records params
func (o *QueryBookingRecordsParams) SetState(state *string) {
	o.State = state
}

// WithTo adds the to to the query booking records params
func (o *QueryBookingRecordsParams) WithTo(to *strfmt.DateTime) *QueryBookingRecordsParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the query booking records params
func (o *QueryBookingRecordsParams) SetTo(to *strfmt.DateTime) {
	o.To = to
}

// WithUser adds the user to the query booking records params
func (o *QueryBookingRecordsParams) WithUser(user *string) *QueryBookingRecordsParams {
	o.SetUser(user)
	return o
}

// SetUser adds the user to the query booking records params
func (o *QueryBookingRecordsParams) SetUser(user *string) {
	o.User = user
}

// WriteToRequest writes these params to a swagger request
func (o *QueryBookingRecordsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.From != nil {

		// query param from
		var qrFrom strfmt.DateTime

		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom.String()
		if qFrom != "" {

			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Policy != nil {

		// query param policy
		var qrPolicy string

		if o.Policy != nil {
			qrPolicy = *o.Policy
		}
		qPolicy := qrPolicy
		if qPolicy != "" {

			if err := r.SetQueryParam("policy", qPolicy); err != nil {
				return err
			}
		}
	}

	if o.Resource != nil {

		// query param resource
		var qrResource string

		if o.Resource != nil {
			qrResource = *o.Resource
		}
		qResource := qrResource
		if qResource != "" {

			if err := r.SetQueryParam("resource", qResource); err != nil {
				return err
			}
		}
	}

	if o.Slot != nil {

		// query param slot
		var qrSlot string

		if o.Slot != nil {
			qrSlot = *o.Slot
		}
		qSlot := qrSlot
		if qSlot != "" {

			if err := r.SetQueryParam("slot", qSlot); err != nil {
				return err
			}
		}
	}

	if o.State != nil {

		// query param state
		var qrState string

		if o.State != nil {
			qrState = *o.State
		}
		qState := qrState
		if qState != "" {

			if err := r.SetQueryParam("state", qState); err != nil {
				return err
			}
		}
	}

	if o.To != nil {

		// query param to
		var qrTo strfmt.DateTime

		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo.String()
		if qTo != "" {

			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}
	}

	if o.User != nil {

		// query param user
		var qrUser string

		if o.User != nil {
			qrUser = *o.User
		}
		qUser := qrUser
		if qUser != "" {

			if err := r.SetQueryParam("user", qUser); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
