// Code generated by go-swagger; DO NOT EDIT.

// Package restapi AdvanceBooking
//
//  User API for booking slots in advance
//  Schemes:
//    http
//  Host: book.practable.io
//  BasePath: /api/v1
//  Version: 0.3
//  Contact: Tim Drysdale<timothy.d.drysdale@gmail.com> https://practable.io
//
//  Consumes:
//    - application/json
//    - text/plain
//
//  Produces:
//    - application/json
//    - text/plain
//
// swagger:meta
package restapi
